'use client';
import {useState} from 'react';
export function OperatorConsole(){
 const [message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage('');const form=e.currentTarget;const fd=new FormData(form);const b=Object.fromEntries(fd.entries());
  try { const payload={...b,netCents:Math.round(Number(b.net)*100),taxCents:Math.round(Number(b.tax)*100),monthlyCredits:b.monthlyCredits===''?null:Number(b.monthlyCredits),operationCost:b.operationCost===''?null:Number(b.operationCost),activeLimit:b.activeLimit===''?null:Number(b.activeLimit),periodStart:new Date(String(b.periodStart)).toISOString(),periodEnd:new Date(String(b.periodEnd)).toISOString()};
  const r=await fetch('/api/operator/contracts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await r.json();if(!r.ok)throw Error(data.error);setMessage('Contrato registrado y plan activado. Comprueba la cuenta del cliente.');form.reset();}catch(e){setMessage(e instanceof Error?e.message:'No se pudo registrar.');}finally{setBusy(false);}
 }
 return <form onSubmit={submit} className="studio-panel space-y-4 max-w-3xl"><p className="studio-notice">Registra solo pagos recibidos y contratos aceptados. Este formulario no firma contratos, no cobra dinero ni emite facturas.</p>
  <label className="studio-field">Identificador de cuenta del cliente<input name="ownerId" required pattern="[0-9a-fA-F-]{36}"/></label>
  <label className="studio-field">Plan<select name="plan"><option>PRO</option><option>BUSINESS</option><option>ENTERPRISE</option></select></label><label className="studio-field">Periodo<select name="billing"><option value="monthly">Mensual</option><option value="annual">Anual</option></select></label>
  <div className="grid sm:grid-cols-2 gap-4"><label className="studio-field">Inicio pagado<input name="periodStart" type="datetime-local" required/></label><label className="studio-field">Fin pagado<input name="periodEnd" type="datetime-local" required/></label><label className="studio-field">Base en euros<input name="net" type="number" min="0" step="0.01" required/></label><label className="studio-field">IVA en euros<input name="tax" type="number" min="0" step="0.01" required/></label></div>
  <label className="studio-field">Medio de pago<select name="paymentMethod"><option value="transfer">Transferencia</option><option value="bizum">Bizum</option><option value="cash">Efectivo</option><option value="card">Tarjeta</option></select></label>
  <label className="studio-field">Referencia única del justificante<input name="reference" minLength={3} maxLength={160} required/></label><label className="studio-field">Referencia del contrato firmado<input name="documentReference" minLength={3} maxLength={500} required/></label>
  <fieldset className="space-y-4"><legend className="font-semibold">Condiciones de IA acordadas</legend><p>Deja en blanco lo que todavía no esté aprobado. La IA de pago permanecerá desactivada.</p><label className="studio-field">Créditos por mes<input name="monthlyCredits" type="number" min="0" max="1000000"/></label><label className="studio-field">Coste por operación<input name="operationCost" type="number" min="1" max="1000000"/></label><label className="studio-field">Campañas simultáneas Enterprise<input name="activeLimit" type="number" min="1" max="10000"/></label></fieldset>
  <label className="flex gap-3"><input type="checkbox" required/> He comprobado el pago, el contrato aceptado y las condiciones introducidas.</label><button className="studio-primary" disabled={busy}>{busy?'Registrando…':'Registrar pago y activar plan'}</button>{message&&<p role="status">{message}</p>}
 </form>;
}
