'use client';
import {useCallback,useEffect,useState} from 'react';
import {ORDER_STATES,type CustomerOrder} from '@/lib/commercial/orders';
export function OperatorOrders(){
 const [orders,setOrders]=useState<CustomerOrder[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const call=useCallback(async (body:object)=>{const r=await fetch('/api/operator/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const a=await r.json();if(!r.ok)throw Error(a.error);return a;},[]);
 const load=useCallback(async()=>{try{setOrders((await call({action:'list'})).orders);}catch(e){setMessage(e instanceof Error?e.message:'No se pudieron cargar.');}},[call]);
 useEffect(()=>{void load();},[load]);
 async function submit(e:React.FormEvent<HTMLFormElement>,id:string){e.preventDefault();if(busy)return;const fd=new FormData(e.currentTarget);setBusy(true);setMessage('');try{await call({id,...Object.fromEntries(fd)});await load();setMessage('Pedido actualizado. El cliente puede ver el estado en su cuenta.');}catch(e){setMessage(e instanceof Error?e.message:'Error al guardar.');}finally{setBusy(false);}}
 return <section className="studio-panel mb-8 space-y-5"><div className="flex flex-wrap justify-between gap-3"><h2 className="text-xl font-semibold">Pedidos recibidos</h2><button className="studio-button" disabled={busy} onClick={load}>Actualizar pedidos</button></div>{message&&<p role="status">{message}</p>}{!orders.length&&<p>No hay pedidos registrados.</p>}{orders.map(o=><article key={o.id} className="border border-emerald-900 rounded-xl p-4 space-y-3"><h3>{o.mode==='test'?'PRUEBA · ':''}{o.product} · {ORDER_STATES[o.state]}</h3><p className="text-sm break-all">Cliente: {o.owner_id} · Pedido: {o.id}</p><p>{((o.net_cents+o.tax_cents)/100).toFixed(2)} € IVA incluido · {o.billing==='annual'?'Anual':'Mensual'}</p>{o.customer_note&&<p>Referencia indicada por el cliente: {o.customer_note}</p>}{o.mode==='manual'&&['requested','awaiting_payment','payment_review'].includes(o.state)&&<><form onSubmit={e=>submit(e,o.id)} className="space-y-3"><input type="hidden" name="action" value="instructions"/><label className="studio-field">Instrucciones de pago y contratación<textarea name="instructions" defaultValue={o.instructions} required minLength={10} maxLength={4000}/></label><button className="studio-button" disabled={busy}>Guardar instrucciones para el cliente</button></form><details><summary className="cursor-pointer py-3">Completar tras registrar el pago verificado</summary><form onSubmit={e=>submit(e,o.id)} className="space-y-3"><input type="hidden" name="action" value="fulfill"/><label className="studio-field">Justificante ya registrado en contratos o recargas<input name="reference" required minLength={3} maxLength={160}/></label><p className="studio-muted">Usa los formularios de activación de esta página. Completar el pedido comprueba el registro existente; no cobra ni añade créditos otra vez.</p><button className="studio-primary" disabled={busy}>Comprobar y completar pedido</button></form></details></>}</article>)}</section>;
}
