"use client";
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {useRemoteSync} from '@/lib/hooks/useRemoteSync';
import {useTiendaEstado} from '@/store/useTiendaEstado';
import type {RemoteCampaign} from '@/lib/supabase/persistence';
export function RemoteSyncPanel(){
 const api=useRemoteSync();const router=useRouter();const [message,setMessage]=useState('');const current=useTiendaEstado(s=>s.datosEscaparate);
 async function act(fn:()=>Promise<{success:boolean;error:string|null}>){setMessage('');const r=await fn();if(r.success)setMessage('Cambios guardados.');}
 function open(c:RemoteCampaign){const s=c.snapshot;useTiendaEstado.setState({adnMarca:s.adnMarca||null,datosEscaparate:s.datosEscaparate||null,imagenSubida:s.imagenSubida||null,galeriaActivos:s.galeriaActivos||[],redesSociales:s.redesSociales||{},slug:c.slug,pasoActual:'ESCAPARATE',cartelesGenerados:[]});useTiendaEstado.getState().guardarCampaña({id:c.id,nombreCampaña:c.name,idEscaparate:c.slug||c.id,idCartel:null,estado:c.status==='active'?'EN_LINEA':'BORRADOR',fechaCreacion:c.created_at,ultimaActualizacion:c.updated_at,snapshot:s,urlPublica:c.slug?'/v/'+c.slug:undefined,metricas:{visitas:0,conversiones:0,escaneos:0,ratioConversion:0,puntajeSaludMarca:0,tendencia:'ESTABLE'}});router.push('/create');}
 const button='rounded-xl border border-white/20 px-4 py-3 text-sm font-semibold hover:bg-white/10 disabled:opacity-40';
 return <section className="rounded-3xl border border-white/10 bg-zinc-950 p-5 text-white space-y-4"><h2 className="text-lg font-bold">Tus campañas en la nube</h2>{!api.user?<p>Para guardar y publicar, <a className="underline text-cyan-300" href="/auth/login">inicia sesión</a> o <a className="underline text-cyan-300" href="/auth/signup">crea tu cuenta</a>. Tus borradores locales se conservan.</p>:<><div className="flex flex-wrap gap-3">{current&&<button className={button+' bg-blue-600'} disabled={api.syncing} onClick={()=>act(api.saveCurrent)}>Guardar escaparate actual</button>}<button className={button} disabled={api.syncing} onClick={()=>act(api.migrateLocalToRemote)}>Guardar borradores locales</button><button className={button} disabled={api.loading||api.syncing} onClick={()=>api.loadRemote()}>Actualizar lista</button></div><p className="text-sm text-white/60">Guardar conserva el borrador. Publicar hace visible su web y activa el enlace del QR. Tras editar una web, guarda y vuelve a publicar para actualizarla.</p>{api.loading&&<p role="status">Cargando campañas…</p>}{api.remoteCampaigns.map(c=><article key={c.id} className="p-4 rounded-2xl border border-white/10 flex flex-wrap gap-3 items-center"><div className="flex-1 min-w-40"><h3 className="font-semibold">{c.name}</h3><p className="text-sm text-white/60">{c.plan} · {c.status==='active'?'Publicada':'Borrador'}</p></div><button className={button} disabled={api.syncing} onClick={()=>open(c)}>Abrir editor</button><button className={button} disabled={api.syncing||!c.slug} onClick={()=>act(()=>api.publish(c.id,c.slug!))}>{c.status==='active'?'Actualizar web':'Publicar'}</button>{c.status==='active'&&<><a className={button} href={'/v/'+encodeURIComponent(c.slug!)} target="_blank" rel="noreferrer">Ver web</a><button className={button} disabled={api.syncing} onClick={()=>act(()=>api.unpublish(c.id))}>Retirar publicación</button></>}</article>)}</>}{api.syncing&&<p role="status">Guardando, espera un momento…</p>}{api.error&&<p role="alert" className="text-red-300">{api.error}</p>}{message&&<p role="status" className="text-emerald-300">{message}</p>}</section>;
}
