import { supabase } from '../lib/supabase';
import type { BrandData, GenerativeStrategy, StrategyGenerationResponse } from '../types';

// API URL from environment variable with fallback
// API Base URL logic
const BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:3000';
// Ensure we don't double-slash or miss /api
const API_URL = BASE_URL.endsWith('/api') ? BASE_URL : `${BASE_URL}/api`;

/**
 * Generates marketing strategies via backend AI service
 */
export async function generateStrategiesFromBackend(
    brandData: BrandData,
    date?: string,
    location?: string
): Promise<StrategyGenerationResponse> {
    try {
        // Get session for authentication
        const { data: { session } } = await supabase.auth.getSession();

        const headers: Record<string, string> = {
            'Content-Type': 'application/json',
        };

        if (session?.access_token) {
            headers['Authorization'] = `Bearer ${session.access_token}`;
        }

        const controller = new AbortController();
        const timeoutId = setTimeout(() => controller.abort(), 5000); // 5s timeout for backend

        const response = await fetch(`${API_URL}/strategies/generate`, {
            method: 'POST',
            headers,
            body: JSON.stringify({
                brandData,
                date,
                location
            }),
            signal: controller.signal
        }).finally(() => clearTimeout(timeoutId));

        if (!response.ok) {
            const errorData = await response.json().catch(() => ({}));
            throw new Error(errorData.details || errorData.error || `Server error: ${response.status}`);
        }

        const data = await response.json();

        // Map backend response to frontend types if necessary, though they should match
        const strategies: GenerativeStrategy[] = data.strategies;

        return {
            success: true,
            strategies: strategies.map(s => ({
                ...s,
                // Ensure backward compatibility with required MarketingStrategy fields if needed
                reasoning: "Generated by AI",
                tactics: [],
                seasonalContext: "Dynamic",
                locationContext: "Dynamic"
            }))
        };
    } catch (error) {
        console.error('[BackendService] Generation error:', error);
        return {
            success: false,
            error: error instanceof Error ? error.message : 'Unknown backend error'
        };
    }
}

/**
 * Health check - verifies backend is alive
 */
export async function checkBackendHealth(): Promise<{ alive: boolean; details?: any }> {
    try {
        const response = await fetch(`${API_URL}/health`, {
            method: 'GET',
            headers: { 'Content-Type': 'application/json' }
        });

        if (!response.ok) {
            return { alive: false };
        }

        const data = await response.json();
        return { alive: true, details: data };
    } catch (error) {
        console.error('[BackendService] Health check failed:', error);
        return { alive: false };
    }
}

/**
 * Interface for poster generation config
 */
interface PosterConfig {
    businessName: string;
    businessType?: string;
    tagline?: string;
    landingUrl: string;
    primaryColor?: string;
    phone?: string;
    address?: string;
}

/**
 * Generates a poster PDF via backend service
 * @returns Blob of the PDF file
 */
export async function generatePosterPdf(config: PosterConfig): Promise<{ success: boolean; blob?: Blob; error?: string }> {
    try {
        // Get session for authentication
        const { data: { session } } = await supabase.auth.getSession();

        const headers: Record<string, string> = {
            'Content-Type': 'application/json',
        };

        if (session?.access_token) {
            headers['Authorization'] = `Bearer ${session.access_token}`;
        }

        const response = await fetch(`${API_URL}/posters/generate`, {
            method: 'POST',
            headers,
            credentials: 'include', // Include cookies for auth compatibility
            body: JSON.stringify(config),
        });

        if (!response.ok) {
            const errorData = await response.json().catch(() => ({}));
            throw new Error(errorData.error || `Server error: ${response.status}`);
        }

        const blob = await response.blob();
        return { success: true, blob };
    } catch (error) {
        console.error('[BackendService] Poster generation error:', error);
        return {
            success: false,
            error: error instanceof Error ? error.message : 'Unknown error generating poster'
        };
    }
}

