/**
 * Premium Landing Code Generator
 * ================================
 * Generates production-ready HTML5 with:
 * - CSS Variables for instant customization
 * - Glassmorphism & premium shadows
 * - Fade-in animations on load
 * - Mobile-first responsive design
 */

import { generateVisualDNAPalette, type ColorPalette } from './colorScience';
import { detectVibe, type VibeProfile } from './vibeAnalysis';
import type { BrandData } from '../types';

// ─────────────────────────────────────────────────────────────
// TYPES
// ─────────────────────────────────────────────────────────────

export interface LandingConfig {
    brandData: BrandData;
    links: LinkItem[];
    landingUrl: string;
    backgroundImageUrl?: string;
}

export interface LinkItem {
    name: string;
    url: string;
    emoji?: string;
    isPrimary?: boolean;
}

export interface GeneratedCode {
    html: string;
    previewUrl?: string;
}

// ─────────────────────────────────────────────────────────────
// CORE CSS FRAMEWORK
// ─────────────────────────────────────────────────────────────

function generatePremiumCSS(palette: ColorPalette, bgUrl: string): string {
    return `
/* ═══════════════════════════════════════════════════════════
   PREMIUM LANDING CSS
   Generated by Foto Fachada - Visual DNA System
═══════════════════════════════════════════════════════════ */

/* ─────────────────────────────────────────────────────────
   CSS VARIABLES (Instant Customization)
───────────────────────────────────────────────────────── */
:root {
    /* Brand Colors */
    --primary: ${palette.primary};
    --primary-dark: ${palette.primaryDark};
    --primary-light: ${palette.primaryLight};
    --secondary: ${palette.secondary};
    --accent: ${palette.accent};
    
    /* Backgrounds */
    --bg-base: ${palette.background};
    --bg-surface: ${palette.surface};
    --bg-image: url('${bgUrl}');
    --bg-overlay: ${palette.overlay};
    
    /* Text */
    --text-primary: ${palette.text};
    --text-secondary: ${palette.textSecondary};
    --text-on-primary: ${palette.textOnPrimary};
    
    /* Effects */
    --glass-bg: rgba(255, 255, 255, 0.05);
    --glass-border: rgba(255, 255, 255, 0.1);
    --glass-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.5);
    --glass-blur: 20px;
    
    /* Shadows - Premium depth */
    --shadow-sm: 0 2px 4px rgba(0, 0, 0, 0.1);
    --shadow-md: 0 4px 12px rgba(0, 0, 0, 0.15);
    --shadow-lg: 0 10px 30px rgba(0, 0, 0, 0.25);
    --shadow-xl: 0 20px 50px rgba(0, 0, 0, 0.35);
    --shadow-glow: 0 0 40px ${palette.primary}55;
    
    /* Button Depth */
    --btn-shadow: 0 8px 25px ${palette.primary}55, 0 4px 8px rgba(0, 0, 0, 0.2);
    --btn-shadow-hover: 0 12px 35px ${palette.primary}77, 0 6px 12px rgba(0, 0, 0, 0.3);
    --btn-inner-light: inset 0 1px 3px rgba(255, 255, 255, 0.25);
    --btn-inner-dark: inset 0 -1px 3px rgba(0, 0, 0, 0.15);
    
    /* Spacing */
    --space-xs: 0.5rem;
    --space-sm: 1rem;
    --space-md: 1.5rem;
    --space-lg: 2rem;
    --space-xl: 3rem;
    
    /* Border Radius */
    --radius-sm: 8px;
    --radius-md: 12px;
    --radius-lg: 20px;
    --radius-xl: 28px;
    --radius-full: 50px;
    
    /* Transitions */
    --transition-fast: 0.15s ease;
    --transition-normal: 0.3s cubic-bezier(0.4, 0, 0.2, 1);
    --transition-slow: 0.5s cubic-bezier(0.4, 0, 0.2, 1);
}

/* ─────────────────────────────────────────────────────────
   BASE RESET & TYPOGRAPHY
───────────────────────────────────────────────────────── */
*, *::before, *::after {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

html {
    font-size: 16px;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}

body {
    font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
    background: var(--bg-base);
    color: var(--text-primary);
    line-height: 1.6;
    min-height: 100vh;
    overflow-x: hidden;
}

/* ─────────────────────────────────────────────────────────
   LAYERED BACKGROUND (Depth Effect)
───────────────────────────────────────────────────────── */
.bg-layer {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    pointer-events: none;
}

.bg-image {
    z-index: -3;
    background: var(--bg-image);
    background-size: cover;
    background-position: center;
    background-attachment: fixed;
    filter: blur(3px) brightness(0.7);
}

.bg-overlay {
    z-index: -2;
    background: linear-gradient(
        135deg,
        var(--bg-overlay) 0%,
        rgba(0, 0, 0, 0.5) 50%,
        var(--bg-overlay) 100%
    );
}

.bg-texture {
    z-index: -1;
    background: 
        radial-gradient(circle at 20% 80%, var(--primary)15 0%, transparent 35%),
        radial-gradient(circle at 80% 20%, var(--secondary)15 0%, transparent 35%);
}

/* ─────────────────────────────────────────────────────────
   GLASSMORPHISM CARD (Premium Effect)
───────────────────────────────────────────────────────── */
.glass-card {
    background: var(--glass-bg);
    backdrop-filter: blur(var(--glass-blur));
    -webkit-backdrop-filter: blur(var(--glass-blur));
    border: 1px solid var(--glass-border);
    border-radius: var(--radius-xl);
    box-shadow: 
        var(--glass-shadow),
        inset 0 1px 0 rgba(255, 255, 255, 0.1),
        inset 0 0 0 1px rgba(255, 255, 255, 0.05);
}

.glass-card::before {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    height: 50%;
    background: linear-gradient(
        to bottom,
        rgba(255, 255, 255, 0.08),
        transparent
    );
    border-radius: var(--radius-xl) var(--radius-xl) 50% 50%;
    pointer-events: none;
}

/* ─────────────────────────────────────────────────────────
   PREMIUM BUTTONS (High-End Feel)
───────────────────────────────────────────────────────── */
.btn {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    gap: 0.75rem;
    padding: 1rem 2rem;
    font-weight: 600;
    font-size: 1rem;
    text-decoration: none;
    border: none;
    cursor: pointer;
    transition: all var(--transition-normal);
    position: relative;
    overflow: hidden;
    
    /* Finger-friendly minimum size */
    min-height: 56px;
    min-width: 120px;
}

.btn-primary {
    background: linear-gradient(135deg, var(--primary) 0%, var(--primary-dark) 100%);
    color: var(--text-on-primary);
    border-radius: var(--radius-md);
    box-shadow: var(--btn-shadow), var(--btn-inner-light), var(--btn-inner-dark);
    border: 1px solid rgba(255, 255, 255, 0.1);
}

/* Shine effect overlay */
.btn-primary::before {
    content: '';
    position: absolute;
    top: 0;
    left: -100%;
    width: 100%;
    height: 100%;
    background: linear-gradient(
        90deg,
        transparent,
        rgba(255, 255, 255, 0.2),
        transparent
    );
    transition: left 0.5s ease;
}

.btn-primary:hover::before {
    left: 100%;
}

.btn-primary:hover {
    transform: translateY(-3px) scale(1.02);
    box-shadow: var(--btn-shadow-hover), var(--btn-inner-light), var(--shadow-glow);
}

.btn-primary:active {
    transform: translateY(0) scale(0.98);
    box-shadow: var(--shadow-sm);
}

.btn-secondary {
    background: rgba(255, 255, 255, 0.08);
    color: var(--text-primary);
    border-radius: var(--radius-md);
    border: 2px solid rgba(255, 255, 255, 0.15);
    backdrop-filter: blur(10px);
}

.btn-secondary:hover {
    background: rgba(255, 255, 255, 0.15);
    border-color: var(--primary);
    transform: translateY(-2px);
}

/* ─────────────────────────────────────────────────────────
   FADE-IN ANIMATIONS
───────────────────────────────────────────────────────── */
.fade-in {
    opacity: 0;
    transform: translateY(20px);
    animation: fadeInUp 0.6s ease forwards;
}

.fade-in-delay-1 { animation-delay: 0.1s; }
.fade-in-delay-2 { animation-delay: 0.2s; }
.fade-in-delay-3 { animation-delay: 0.3s; }
.fade-in-delay-4 { animation-delay: 0.4s; }
.fade-in-delay-5 { animation-delay: 0.5s; }

@keyframes fadeInUp {
    from {
        opacity: 0;
        transform: translateY(20px);
    }
    to {
        opacity: 1;
        transform: translateY(0);
    }
}

@keyframes pulse {
    0%, 100% { opacity: 1; }
    50% { opacity: 0.7; }
}

@keyframes float {
    0%, 100% { transform: translateY(0); }
    50% { transform: translateY(-10px); }
}

/* ─────────────────────────────────────────────────────────
   LAYOUT
───────────────────────────────────────────────────────── */
.landing-container {
    min-height: 100vh;
    display: flex;
    align-items: center;
    justify-content: center;
    padding: var(--space-md);
}

.landing-content {
    width: 100%;
    max-width: 420px;
    position: relative;
}

.landing-card {
    padding: var(--space-xl);
    text-align: center;
}

.header {
    margin-bottom: var(--space-lg);
}

.business-name {
    font-size: clamp(1.75rem, 7vw, 2.5rem);
    font-weight: 700;
    letter-spacing: -0.02em;
    color: var(--text-primary);
    margin-bottom: 0.25rem;
}

.business-type {
    font-size: 0.85rem;
    text-transform: uppercase;
    letter-spacing: 0.15em;
    color: var(--primary);
    font-weight: 500;
}

.tagline {
    font-size: clamp(1rem, 4vw, 1.25rem);
    color: var(--text-secondary);
    margin-bottom: var(--space-lg);
    line-height: 1.5;
}

.actions {
    display: flex;
    flex-direction: column;
    gap: var(--space-sm);
    margin-bottom: var(--space-lg);
}

.footer {
    padding-top: var(--space-md);
    border-top: 1px solid rgba(255, 255, 255, 0.1);
}

.social-icons {
    display: flex;
    justify-content: center;
    gap: var(--space-md);
    margin-bottom: var(--space-sm);
}

.social-icon {
    width: 40px;
    height: 40px;
    display: flex;
    align-items: center;
    justify-content: center;
    border-radius: 50%;
    background: rgba(255, 255, 255, 0.1);
    color: var(--text-primary);
    transition: all var(--transition-normal);
}

.social-icon:hover {
    background: var(--primary);
    transform: scale(1.1);
}

.social-icon svg {
    width: 20px;
    height: 20px;
}

.address-link {
    display: block;
    font-size: 0.85rem;
    color: var(--text-secondary);
    text-decoration: none;
    margin-bottom: 0.5rem;
    transition: color var(--transition-fast);
}

.address-link:hover {
    color: var(--primary);
}

.business-hours {
    font-size: 0.75rem;
    color: var(--text-secondary);
    opacity: 0.8;
}

.powered-by {
    margin-top: var(--space-sm);
    font-size: 0.65rem;
    color: var(--text-secondary);
    opacity: 0.6;
}

/* ─────────────────────────────────────────────────────────
   RESPONSIVE (Mobile-First)
───────────────────────────────────────────────────────── */
@media (max-width: 480px) {
    .landing-container {
        padding: var(--space-sm);
    }
    
    .landing-card {
        padding: var(--space-lg) var(--space-md);
        border-radius: var(--radius-lg);
    }
    
    .btn {
        width: 100%;
        padding: 1.125rem 1.5rem;
        font-size: 1.05rem;
        min-height: 60px; /* Extra finger-friendly on mobile */
    }
}

@media (min-width: 768px) {
    .landing-content {
        max-width: 480px;
    }
}
    `;
}

// ─────────────────────────────────────────────────────────────
// SOCIAL ICONS SVG
// ─────────────────────────────────────────────────────────────

const SOCIAL_ICONS = {
    instagram: `<svg viewBox="0 0 24 24" fill="currentColor"><path d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.163 6.162 6.163 6.162-2.759 6.162-6.163c0-3.403-2.759-6.162-6.162-6.162zm0 10.162c-2.209 0-4-1.79-4-4 0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.21-1.791 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z"/></svg>`,

    facebook: `<svg viewBox="0 0 24 24" fill="currentColor"><path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z"/></svg>`,

    whatsapp: `<svg viewBox="0 0 24 24" fill="currentColor"><path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413z"/></svg>`
};

// ─────────────────────────────────────────────────────────────
// HTML GENERATOR
// ─────────────────────────────────────────────────────────────

function generateHTML(
    config: LandingConfig,
    vibe: VibeProfile,
    css: string
): string {
    const { brandData, links, landingUrl } = config;

    // Generate links HTML
    const linksHTML = links.map((link, index) => `
        <a href="${link.url || '#'}" 
           class="btn ${link.isPrimary !== false ? 'btn-primary' : 'btn-secondary'} fade-in fade-in-delay-${Math.min(index + 3, 5)}">
            ${link.emoji ? `<span>${link.emoji}</span>` : ''}
            <span>${link.name}</span>
        </a>
    `).join('');

    // Social links
    const instagram = brandData.instagram || '';
    const facebook = brandData.facebook || '';
    const whatsapp = brandData.whatsapp || '';
    const address = brandData.address || '';
    const hours = brandData.hours || 'L-V 10:00-20:00';

    return `<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">
    <title>${brandData.name} | ${brandData.businessType}</title>
    <meta name="description" content="${brandData.tagline || `Descubre ${brandData.name}`}">
    
    <!-- OpenGraph -->
    <meta property="og:title" content="${brandData.name}">
    <meta property="og:description" content="${brandData.tagline || ''}">
    <meta property="og:type" content="website">
    <meta property="og:url" content="${landingUrl}">
    <meta property="og:locale" content="es_ES">
    
    <!-- Twitter Card -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="${brandData.name}">
    <meta name="twitter:description" content="${brandData.tagline || ''}">
    
    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=${encodeURIComponent(vibe.typography[0])}:wght@400;600;700&family=Inter:wght@400;500;600&display=swap" rel="stylesheet">
    
    <style>
        ${css}
        
        /* Custom Font for this vibe */
        .business-name {
            font-family: '${vibe.typography[0]}', 'Inter', sans-serif;
        }
    </style>
</head>
<body>
    <!-- Layered Background for Depth -->
    <div class="bg-layer bg-image"></div>
    <div class="bg-layer bg-overlay"></div>
    <div class="bg-layer bg-texture"></div>
    
    <div class="landing-container">
        <div class="landing-content">
            <div class="landing-card glass-card">
                <!-- Header -->
                <header class="header fade-in fade-in-delay-1">
                    <h1 class="business-name">${brandData.name}</h1>
                    <span class="business-type">${brandData.businessType}</span>
                </header>
                
                <!-- Tagline -->
                <p class="tagline fade-in fade-in-delay-2">
                    ${brandData.tagline || 'Tu destino favorito'}
                </p>
                
                <!-- Action Buttons -->
                <nav class="actions">
                    ${linksHTML}
                </nav>
                
                <!-- Smart Footer -->
                <footer class="footer fade-in fade-in-delay-5">
                    ${(instagram || facebook || whatsapp) ? `
                    <div class="social-icons">
                        ${instagram ? `<a href="https://instagram.com/${instagram}" class="social-icon" aria-label="Instagram">${SOCIAL_ICONS.instagram}</a>` : ''}
                        ${facebook ? `<a href="https://facebook.com/${facebook}" class="social-icon" aria-label="Facebook">${SOCIAL_ICONS.facebook}</a>` : ''}
                        ${whatsapp ? `<a href="https://wa.me/${whatsapp.replace(/[^0-9]/g, '')}" class="social-icon" aria-label="WhatsApp">${SOCIAL_ICONS.whatsapp}</a>` : ''}
                    </div>
                    ` : ''}
                    
                    ${address ? `
                    <a href="https://maps.google.com/?q=${encodeURIComponent(address)}" class="address-link" target="_blank">
                        📍 ${address}
                    </a>
                    ` : ''}
                    
                    <p class="business-hours">🕐 ${hours}</p>
                    
                    <p class="powered-by">Creado con Foto Fachada</p>
                </footer>
            </div>
        </div>
    </div>
    
    <script>
    // Lightweight entrance animations enhancer
    (function() {
        // Intersection Observer for scroll-triggered animations
        const observer = new IntersectionObserver((entries) => {
            entries.forEach(entry => {
                if (entry.isIntersecting) {
                    entry.target.style.animationPlayState = 'running';
                }
            });
        }, { threshold: 0.1 });
        
        // Observe all fade-in elements
        document.querySelectorAll('.fade-in').forEach(el => {
            el.style.animationPlayState = 'paused';
            observer.observe(el);
        });
        
        // Trigger animations on load
        window.addEventListener('load', () => {
            document.querySelectorAll('.fade-in').forEach(el => {
                el.style.animationPlayState = 'running';
            });
        });
        
        // Button ripple effect
        document.querySelectorAll('.btn').forEach(btn => {
            btn.addEventListener('click', function(e) {
                const ripple = document.createElement('span');
                const rect = this.getBoundingClientRect();
                const x = e.clientX - rect.left;
                const y = e.clientY - rect.top;
                
                ripple.style.cssText = \`
                    position: absolute;
                    background: rgba(255,255,255,0.3);
                    border-radius: 50%;
                    transform: scale(0);
                    animation: ripple 0.6s ease-out;
                    pointer-events: none;
                    left: \${x}px;
                    top: \${y}px;
                    width: 100px;
                    height: 100px;
                    margin-left: -50px;
                    margin-top: -50px;
                \`;
                
                this.appendChild(ripple);
                setTimeout(() => ripple.remove(), 600);
            });
        });
    })();
    </script>
    
    <style>
    @keyframes ripple {
        to {
            transform: scale(4);
            opacity: 0;
        }
    }
    </style>
</body>
</html>`;
}

// ─────────────────────────────────────────────────────────────
// PUBLIC API
// ─────────────────────────────────────────────────────────────

/**
 * Generate a complete, production-ready landing page
 */
export function generatePremiumLanding(config: LandingConfig): GeneratedCode {
    const { brandData } = config;

    // Detect vibe from business type
    const vibe = detectVibe(brandData.businessType);

    // Generate color palette
    const primaryColor = brandData.colors?.primary || '#6366f1';
    const palette = generateVisualDNAPalette(primaryColor, 'modern');

    // Background image URL (Unsplash)
    const bgKeyword = encodeURIComponent(brandData.businessType.toLowerCase());
    const bgUrl = config.backgroundImageUrl ||
        `https://source.unsplash.com/1920x1080/?${bgKeyword}`;

    // Generate CSS
    const css = generatePremiumCSS(palette, bgUrl);

    // Generate HTML
    const html = generateHTML(config, vibe, css);

    return { html };
}

/**
 * Quick generation with minimal config
 */
export function quickGenerateLanding(
    name: string,
    businessType: string,
    primaryColor: string,
    links: LinkItem[]
): GeneratedCode {
    return generatePremiumLanding({
        brandData: {
            name,
            businessType,
            colors: {
                primary: primaryColor,
                secondary: '#4b5563', // Default neutral
                accent: primaryColor   // Default to primary
            },
            tagline: '',
            style: 'modern',
            description: `Generated landing page for ${name}`,
            typography: 'Inter'
        } as BrandData,
        links,
        landingUrl: (() => {
            const isDev = import.meta.env.DEV;
            const protocol = isDev ? 'http' : 'https';
            const domain = isDev ? 'localhost:3000' : 'foto-fachada-v1.vercel.app';
            return `${protocol}://${domain}/l/${name.toLowerCase().replace(/\s+/g, '-')}`;
        })()
    });
}
