'use client';
import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { CREDIT_POLICY } from '@/lib/commercial/credits';
import { orderPrice, ORDER_STATES, type CustomerOrder, type OrderInput } from '@/lib/commercial/orders';
const euros=(c:number)=>(c/100).toLocaleString('es-ES',{style:'currency',currency:'EUR'});
export function Checkout(){
 const [selection,setSelection]=useState<OrderInput>({kind:'plan',product:'PRO',billing:'annual',mode:'manual'});
 const [orders,setOrders]=useState<CustomerOrder[]>([]),[current,setCurrent]=useState<CustomerOrder|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[guest,setGuest]=useState(false),[note,setNote]=useState(''),[ready,setReady]=useState(false);
 const requestId=useRef('');
 useEffect(()=>{const p=new URLSearchParams(location.search);setSelection({kind:p.get('kind')==='credits'?'credits':'plan',product:p.get('kind')==='credits'?(CREDIT_POLICY.packs.some(x=>x.id===p.get('pack'))?p.get('pack')!:'small'):p.get('plan')==='BUSINESS'?'BUSINESS':'PRO',billing:p.get('billing')==='monthly'?'monthly':'annual',mode:p.get('mode')==='test'?'test':'manual'});setReady(true);void load();},[]);
 async function load(){try{const r=await fetch('/api/orders',{cache:'no-store'});const a=await r.json();setGuest(r.status===401);if(r.status===401)return;if(!r.ok)throw Error(a.error);setOrders(a.orders);setError('');}catch(e){setError(e instanceof Error?e.message:'No se pudieron cargar los pedidos.');}}
 function change(part:Partial<OrderInput>){setSelection(s=>({...s,...part}));requestId.current='';setCurrent(null);setError('');}
 async function request(){if(busy)return;setBusy(true);setError('');requestId.current ||= crypto.randomUUID();try{const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...selection,requestId:requestId.current})});const a=await r.json();if(!r.ok)throw Error(a.error);setCurrent(a.order);await load();}catch(e){setError(e instanceof Error?e.message:'No se pudo crear el pedido.');}finally{setBusy(false);}}
 async function update(action:string){if(!current||busy)return;setBusy(true);setError('');try{const r=await fetch('/api/orders',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:current.id,action,note})});const a=await r.json();if(!r.ok)throw Error(a.error);setCurrent(a.order);await load();window.dispatchEvent(new Event('innova-account-updated'));}catch(e){setError(e instanceof Error?e.message:'No se pudo actualizar.');}finally{setBusy(false);}}
 const price=orderPrice(selection), back='/checkout?'+new URLSearchParams({kind:selection.kind,plan:selection.product,pack:selection.product,billing:selection.billing,mode:selection.mode});
 return <div className="space-y-6"><Link href="/dashboard" className="studio-button">← Mi panel</Link><header><p className="studio-eyebrow">PLANES Y CRÉDITOS</p><h1 className="text-3xl font-semibold mt-3">{selection.kind==='credits'?'Recargar créditos IA':'Contratar mi escaparate'}</h1><p className="studio-muted mt-3">Elige tu opción, revisa el importe y sigue el estado desde aquí.</p></header>
 <div className="grid md:grid-cols-2 gap-6"><section className="studio-panel space-y-5"><fieldset disabled={busy||!ready} className="space-y-4"><legend className="font-semibold mb-4">1. Elige tu producto</legend><label className="studio-field">Producto<select value={selection.kind} onChange={e=>change({kind:e.target.value as 'plan'|'credits',product:e.target.value==='plan'?'PRO':'small'})}><option value="plan">Plan de escaparates</option><option value="credits">Recarga de créditos</option></select></label><label className="studio-field">{selection.kind==='plan'?'Plan':'Pack'}<select value={selection.product} onChange={e=>change({product:e.target.value})}>{selection.kind==='plan'?<><option value="PRO">Pro · 5 campañas activas</option><option value="BUSINESS">Business · 10 campañas activas</option></>:CREDIT_POLICY.packs.map(p=><option key={p.id} value={p.id}>{p.credits} créditos · {euros(p.netCents)} + IVA</option>)}</select></label>{selection.kind==='plan'&&<label className="studio-field">Periodo<select value={selection.billing} onChange={e=>change({billing:e.target.value as 'monthly'|'annual'})}><option value="annual">Anual · oferta de lanzamiento</option><option value="monthly">Mensual</option></select></label>}<label className="studio-field">Forma de tramitación<select value={selection.mode} onChange={e=>change({mode:e.target.value as 'manual'|'test'})}><option value="manual">Contratación asistida · Bizum, transferencia o efectivo</option><option value="test">Pasarela de prueba · sin dinero real</option></select></label></fieldset></section>
 <section className="studio-panel space-y-4"><h2 className="font-semibold">2. Revisa el pedido</h2><dl className="space-y-2"><div className="flex justify-between"><dt>Base</dt><dd>{euros(price.netCents)}</dd></div><div className="flex justify-between"><dt>IVA (21 %)</dt><dd>{euros(price.taxCents)}</dd></div><div className="flex justify-between text-xl font-semibold"><dt>Total</dt><dd>{euros(price.netCents+price.taxCents)}</dd></div></dl>{selection.kind==='plan'&&<p className="studio-muted">1.000 créditos al mes, acumulables. Generación inicial incluida. Regeneración completa: {selection.product==='PRO'?200:100} créditos; individual: {selection.product==='PRO'?100:50}.</p>}
 <p className="studio-notice">{selection.mode==='test'?'MODO DE PRUEBA. Simula el pago con una tarjeta ficticia. No introduzcas datos reales. No activa planes ni créditos de producción.':'Registraremos tu solicitud en tu cuenta. INNOVA confirmará las condiciones y publicará aquí las instrucciones de pago. El plan se activa tras aceptar el contrato y verificar el pago.'}</p>{selection.kind==='plan'&&selection.billing==='annual'&&<p className="studio-muted text-sm">Oferta para los primeros 50 clientes. La disponibilidad y cualquier diferencia por cambio de plan se confirman antes de pagar.</p>}
 {guest?<div className="flex flex-wrap gap-3"><Link className="studio-primary" href={'/auth/login?next='+encodeURIComponent(back)}>Iniciar sesión y continuar</Link><Link className="studio-button" href={'/auth/signup?next='+encodeURIComponent(back)}>Crear cuenta</Link></div>:<button className="studio-primary w-full" disabled={busy||!ready} onClick={request}>{busy?'Procesando…':selection.mode==='test'?'Abrir pasarela de prueba':'Registrar solicitud de contratación'}</button>}<Link className="text-sm underline block" href="/legal/terminos">Consultar condiciones del servicio</Link></section></div>
 {error&&<p role="alert" className="studio-notice">{error}</p>}
 {current&&<section className="studio-panel space-y-4" aria-live="polite"><h2 className="text-xl font-semibold">{ORDER_STATES[current.state]}</h2><p className="text-sm break-all">Pedido {current.id}</p><p>Total: {euros(current.net_cents+current.tax_cents)} {current.mode==='test'?'(simulado)':''}</p>{current.mode==='test'&&['requested','test_failed'].includes(current.state)&&<><div className="rounded-xl border border-emerald-800 p-5"><p>Tarjeta ficticia · 4242 4242 4242 4242</p><p className="studio-muted">12/30 · CVC 123 · Cliente de prueba</p></div><div className="flex flex-wrap gap-3"><button disabled={busy} className="studio-primary" onClick={()=>update('test_success')}>Simular pago aprobado</button><button disabled={busy} className="studio-button" onClick={()=>update('test_failure')}>Simular rechazo</button></div></>}{current.state==='test_succeeded'&&<p>Recibo de prueba. No se ha realizado ningún cargo ni se ha modificado tu suscripción. Puedes volver a elegir un producto para hacer otra prueba.</p>}{current.mode==='manual'&&<><p className="whitespace-pre-wrap">{current.instructions||'Tu solicitud está registrada. El equipo preparará el contrato y las instrucciones de pago. Puedes volver a este pedido desde tu panel.'}</p>{current.state==='awaiting_payment'&&<><label className="studio-field">Referencia de tu pago (sin datos bancarios)<input maxLength={500} value={note} onChange={e=>setNote(e.target.value)}/></label><button className="studio-primary" disabled={busy||note.trim().length<3} onClick={()=>update('payment_sent')}>Ya he realizado el pago · solicitar verificación</button></>}</>}{['requested','awaiting_payment'].includes(current.state)&&<button className="studio-button" disabled={busy} onClick={()=>update('cancel')}>Cancelar solicitud</button>}</section>}
 {!guest&&<section id="pedidos" className="studio-panel space-y-4 scroll-mt-24"><div className="flex justify-between gap-3"><h2 className="text-xl font-semibold">Mis pedidos</h2><button className="studio-button" onClick={load}>Actualizar</button></div>{orders.length===0?<p className="studio-muted">Todavía no tienes pedidos.</p>:<ul className="space-y-3">{orders.map(o=><li key={o.id}><button className="studio-button w-full text-left flex-wrap justify-between" onClick={()=>{setCurrent(o);setNote('');}}><span>{o.kind==='plan'?o.product:o.credits+' créditos'} · {o.mode==='test'?'PRUEBA · ':''}{ORDER_STATES[o.state]}</span><span>{euros(o.net_cents+o.tax_cents)} · {new Date(o.created_at).toLocaleDateString('es-ES')}</span></button></li>)}</ul>}</section>}
 </div>;
}
