'use client';
import Script from 'next/script';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
type PaddleBrowser={Environment:{set:(v:'sandbox')=>void};Initialize:(v:{token:string;eventCallback:(e:{name:string})=>void})=>void;Update:(v:{eventCallback:(e:{name:string})=>void})=>void;Checkout:{open:(v:{transactionId:string;settings:{displayMode:'overlay';locale:'es';allowLogout:false}})=>void}};
let initializedToken='';
type Session={id:string;kind:string;product:string;billing:string;state:string};
export function PaddleCheckout(){
 const [configured,setConfigured]=useState(false),[token,setToken]=useState(''),[ready,setReady]=useState(false),[guest,setGuest]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[sessions,setSessions]=useState<Session[]>([]);
 const [product,setProduct]=useState('PRO'),[billing,setBilling]=useState('monthly');const requestId=useRef('');
 async function refresh(){try{const r=await fetch('/api/paddle/checkout',{cache:'no-store'});const d=await r.json();setGuest(r.status===401);if(r.status===401)return;if(!r.ok)throw Error(d.error);setConfigured(d.configured);setToken(d.clientToken||'');setSessions(d.sessions||[]);}catch{setError('No se pudo consultar el estado. Vuelve a intentarlo.');}}
 useEffect(()=>{void refresh();},[]);
 function initialize(){try{const p=(window as unknown as {Paddle:PaddleBrowser}).Paddle;const eventCallback=(e:{name:string})=>{if(e.name==='checkout.completed'){setMessage('Pago enviado. La confirmación definitiva aparecerá en el historial cuando Paddle la comunique al servidor.');void refresh();}};if(initializedToken&&initializedToken!==token)throw Error();if(initializedToken)p.Update({eventCallback});else{p.Environment.set('sandbox');p.Initialize({token,eventCallback});initializedToken=token;}setReady(true);}catch{setError('No se pudo iniciar Paddle. Recarga la página para reintentarlo.');}}
 async function pay(){if(busy||!ready)return;setBusy(true);setError('');requestId.current ||= crypto.randomUUID();try{const r=await fetch('/api/paddle/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:['PRO','BUSINESS'].includes(product)?'plan':'credits',product,billing,requestId:requestId.current})});const d=await r.json();if(!r.ok)throw Error(d.error);(window as unknown as {Paddle:PaddleBrowser}).Paddle.Checkout.open({transactionId:d.transactionId,settings:{displayMode:'overlay',locale:'es',allowLogout:false}});await refresh();}catch(e){setError(e instanceof Error?e.message:'No se pudo abrir Paddle.');}finally{setBusy(false);}}
 return <div className="studio-shell max-w-3xl mx-auto space-y-6"><Link href="/checkout" className="studio-button">← Planes y pedidos</Link><h1 className="text-3xl font-semibold">Pago con Paddle</h1><p className="studio-notice">Entorno Sandbox · pagos de prueba, sin cargos reales. Esta prueba no activa tu suscripción ni añade créditos a tu cuenta real.</p>
 {guest?<Link href="/auth/login?next=%2Fcheckout%2Fpaddle" className="studio-primary">Iniciar sesión para probar</Link>:<>
 {!configured&&<p role="status">Estamos conectando la cuenta de Paddle. Mientras tanto puedes usar la contratación asistida o el simulador.</p>}
 <fieldset disabled={!configured||busy} className="studio-panel space-y-4"><legend>Elige qué quieres probar</legend><label className="studio-field">Producto<select value={product} onChange={e=>{setProduct(e.target.value);requestId.current='';setError('');}}><option value="PRO">Pro · 5 campañas activas</option><option value="BUSINESS">Business · 10 campañas activas</option><option value="small">Recarga · 200 créditos</option><option value="medium">Recarga · 600 créditos</option><option value="large">Recarga · 1.400 créditos</option></select></label>{['PRO','BUSINESS'].includes(product)&&<label className="studio-field">Periodo<select value={billing} onChange={e=>{setBilling(e.target.value);requestId.current='';setError('');}}><option value="monthly">Mensual</option><option value="annual">Anual · tarifa de lanzamiento de prueba</option></select></label>}<p>Paddle mostrará el desglose fiscal y el total antes de confirmar. No introduzcas una tarjeta real en Sandbox.</p><button className="studio-primary" disabled={!ready||busy} onClick={pay}>{busy?'Preparando pago…':'Abrir Paddle Sandbox'}</button></fieldset>
 <section className="studio-panel space-y-3"><div className="flex justify-between gap-3"><h2 className="text-xl font-semibold">Pruebas de Paddle</h2><button className="studio-button" onClick={refresh}>Actualizar estado</button></div>{sessions.length===0?<p>Todavía no hay pruebas registradas.</p>:<ul>{sessions.map(s=><li key={s.id} className="py-3 border-b border-emerald-900">{s.product} · {s.state==='completed'?'Pago confirmado por Paddle · sin activación real':s.state==='ready'?'Pendiente de completar el pago':'En proceso · pendiente de confirmación'}</li>)}</ul>}</section></>}
 {message&&<p role="status">{message}</p>}{error&&<p role="alert">{error}</p>}
 {configured&&token&&<Script src="https://cdn.paddle.com/paddle/v2/paddle.js" onReady={initialize} onError={()=>setError('No se pudo cargar Paddle. Revisa tu conexión.')}/>}
 </div>;
}
