// One renderer for sales demos, editor previews and published customer pages.
let assetRoot;
function initAssets(){ assetRoot = new URL((process.env.NEXT_PUBLIC_BASE_PATH || '') + '/design-references/', window.location.origin); }
const cache = new Map();
async function resource(file, json=false) {
  if (!cache.has(file)) cache.set(file, fetch(new URL(file,assetRoot)).then(r=>{if(!r.ok)throw Error('No se pudo cargar el diseño');return json?r.json():r.text();}).catch(e=>{cache.delete(file);throw e;}));
  return cache.get(file);
}
export const escapeHTML = v => String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const e=escapeHTML;
export function safeURL(value) {
  if(!value)return '';if(typeof value==='string'&&/^#[a-zA-Z0-9_-]+$/.test(value))return value;try {const u=new URL(value,assetRoot);return ['https:','http:','tel:','mailto:'].includes(u.protocol)?u.href:'';}catch{return '';}
}
export function safeImageURL(value) { return typeof value==='string' && /^data:image\/(png|jpeg|webp|gif);base64,[a-z0-9+/=]+$/i.test(value) ? value : safeURL(value); }
export function selectTemplate(business={},content={}) {
  const category=String(business.category||content.category||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
  const plan=String(business.plan||content.plan||'FREE').toUpperCase();
  const premium=plan==='ESCAPARATE';
  const keys=premium?['detail','clinic','dining']:['salamandra','sofia','mango','quinchuqui','belleza'];
  if(keys.includes(content.templateId))return content.templateId;
  if(premium)return /taller|auto|motor|lavado|mecan/.test(category)?'detail':/clinic|estet|belleza|peluq|salud/.test(category)?'clinic':'dining';
  return /moda|tienda|ropa/.test(category)&&!/alimento/.test(category)?'sofia':/frut|alimento/.test(category)?'mango':/belleza|peluq|estet|clinic/.test(category)?'belleza':/ecuador/.test(category)?'quinchuqui':'salamandra';
}
function contactLinks(b) {
  const phone=String(b.phone||'').replace(/[^+\d]/g,'');const wa=String(b.whatsapp||'').replace(/\D/g,'');
  return [wa&&{text:'WhatsApp',url:'https://wa.me/'+wa,action:'whatsapp'},phone&&{text:'Llámanos',url:'tel:'+phone,action:'phone'},b.address&&{text:'Cómo llegar',url:'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(b.address),action:'maps'},safeURL(b.website)&&{text:'Visitar web',url:safeURL(b.website),action:'link'},b.email&&{text:'Escríbenos',url:'mailto:'+String(b.email).replace(/[\r\n]/g,''),action:'email'},b.instagram&&{text:'Instagram',url:safeURL(String(b.instagram).startsWith('http')?b.instagram:'https://www.instagram.com/'+String(b.instagram).replace(/^@/,'')),action:'instagram'}].filter(Boolean);
}
function ctaURL(s,b,links) {return safeURL(s.url)||links.find(l=>l.action===s.action||s.action==='call'&&l.action==='phone')?.url||links[0]?.url||'#contacto';}
function anchor(label,url,cls='visual-button',track='contact') {return `<a class="${cls}" href="${e(url)}" ${url.startsWith('#')?'':'target="_blank" rel="noopener noreferrer"'} data-track="${e(track)}">${e(label)}</a>`;}
const sharedCSS=`*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;overflow-wrap:anywhere}img{max-width:100%}a,button{touch-action:manipulation}a:focus-visible,button:focus-visible{outline:3px solid var(--accent);outline-offset:5px}section{scroll-margin-top:72px}.visual-shell>div:first-of-type{max-width:100%}.visual-shell{max-width:920px;margin:auto}.visual-brand{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:18px 24px;border-bottom:1px solid var(--line);font-weight:700}.visual-brand a{color:inherit;text-decoration:none;font-size:12px;letter-spacing:.12em}.visual-brand img{width:42px;height:42px;object-fit:contain}.visual-button{display:inline-flex;align-items:center;justify-content:center;min-height:48px;padding:14px 22px;border-radius:8px;background:var(--accent);color:var(--button-text,#fff);font-size:13px;font-weight:700;font-family:inherit;text-decoration:none;border:0;cursor:pointer;transition:transform .2s}.visual-button:hover{transform:translateY(-2px)}.visual-section{padding:36px 24px;border-bottom:1px solid var(--line)}.visual-section h2{font-size:clamp(24px,3vw,34px);letter-spacing:-.04em;margin:0 0 16px;line-height:1.15}.visual-section p{color:var(--muted);line-height:1.7;font-size:15px}.visual-kicker{font-size:10px;letter-spacing:.2em;text-transform:uppercase;color:var(--accent);font-weight:700;margin:0 0 12px}.visual-cards{display:grid;gap:16px}.visual-card{background:var(--surface);border:1px solid var(--line);border-radius:12px;padding:24px}.visual-card h3{font-size:20px;font-weight:700;letter-spacing:-.03em;margin:0 0 12px}.visual-card p{margin:0;color:var(--muted);line-height:1.6}.visual-gallery{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.visual-gallery img{display:block;aspect-ratio:3/4;width:100%;object-fit:cover;border-radius:12px}.visual-contact-links{display:flex;flex-wrap:wrap;gap:12px}.visual-foot{padding:28px 24px 110px;font-size:11px;text-align:center;color:var(--muted);letter-spacing:.12em}.visual-tabs{position:fixed;bottom:0;left:50%;transform:translateX(-50%);width:100%;max-width:920px;display:flex;justify-content:space-around;gap:8px;background:var(--nav);backdrop-filter:blur(16px);border-top:1px solid var(--line);padding:18px 12px calc(18px + env(safe-area-inset-bottom));z-index:30}.visual-tabs a{font-size:11px;text-decoration:none;color:var(--text);min-height:32px;display:flex;align-items:center}.visual-demo-note{background:var(--surface);padding:10px 16px;text-align:center;font-size:11px;color:var(--muted)}@media(min-width:700px){.visual-cards{grid-template-columns:repeat(2,minmax(0,1fr))}.visual-section{padding:48px}.visual-gallery{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}*,*:before,*:after{animation:none!important;transition:none!important}}`;
export async function buildLandingDocument({business={},content={},preview=false}={}) {
  initAssets();
  const catalog=await resource('catalog.json',true);const id=selectTemplate(business,content);const premium=!!catalog.premium[id];const plan=String(business.plan||content.plan||'FREE').toUpperCase();
  const sections=Array.isArray(content.sections)?content.sections.filter(x=>x&&typeof x==='object'):[];
  const links=contactLinks(business);const name=content.title||business.name||'Escaparate digital';const subtitle=content.subtitle||business.category||'';
  const firstCTA=sections.find(s=>s.type==='cta')||{};const primaryURL=ctaURL(firstCTA,business,links);const primaryText=firstCTA.text||links[0]?.text||'Conócenos';
  const selected=catalog.simple[id]||{};const accent=premium?({detail:'#135bec',clinic:'#137fec',dining:'#f49d25'}[id]):selected.accent;
  const dark=id==='detail';const palette=`--accent:${accent||'#c9a45c'};--text:${dark?'#ffffff':'#181511'};--muted:${dark?'#aab7c9':'#62605b'};--surface:${dark?'#1c1f27':'#fff'};--line:${dark?'#ffffff18':'#e9e6e0'};--nav:${dark?'#101622ee':'#ffffffee'};--button-text:${premium?'#fff':'#1a1000'};`;
  const sectionHTML=sections.filter(s=>!['hero','cta','gallery'].includes(s.type)).map((s,i)=>`<section class="visual-section" id="section-${i}"><div class="visual-kicker">${e(business.category||subtitle)}</div>${s.title?`<h2>${e(s.title)}</h2>`:''}${s.text?`<p>${e(s.text)}</p>`:''}${Array.isArray(s.items)?`<div class="visual-cards">${s.items.map((item,j)=>`<article class="visual-card"><div class="visual-kicker">${String(j+1).padStart(2,'0')}</div><h3>${e(typeof item==='object'?item.title||item.name:item)}</h3>${typeof item==='object'&&item.text?`<p>${e(item.text)}</p>`:''}${typeof item==='object'&&item.price?`<p>${e(item.price)}</p>`:''}</article>`).join('')}</div>`:''}</section>`).join('');
  const gallery=Array.isArray(content.gallery)?content.gallery:sections.find(s=>s.type==='gallery')?.items||[];
  const photos=gallery.map(x=>typeof x==='string'?{url:x,alt:business.category||name}:x).filter(x=>x&&safeImageURL(x.url||x.src));
  const galleryHTML=photos.length?`<section class="visual-section" id="galeria"><div class="visual-kicker">En imágenes</div><h2>${e(content.galleryTitle||'Nuestro universo')}</h2><div class="visual-gallery">${photos.map(x=>`<img src="${e(safeImageURL(x.url||x.src))}" alt="${e(x.alt||name)}" loading="lazy">`).join('')}</div></section>`:'';
  const contact=`<section class="visual-section" id="contacto"><div class="visual-kicker">${e(name)}</div><h2>${links.length?'Hablemos':'Conócenos'}</h2>${business.description?`<p>${e(business.description)}</p>`:''}${business.address?`<p>${e(business.address)}</p>`:''}${links.length?`<div class="visual-contact-links">${links.map(l=>anchor(l.text,l.url,'visual-button',l.action)).join('')}</div>`:preview?'<p>Esta es una vista de diseño. Los botones de contacto se activan al completar los datos del negocio.</p>':''}</section>`;
  let head='',body='',htmlClass='';
  if(premium){
    const original=await resource(id+'.html');const doc=new DOMParser().parseFromString(original,'text/html');
    doc.querySelectorAll('script').forEach(n=>n.remove());doc.querySelectorAll('[src],[href],[style]').forEach(el=>{for(const attr of ['src','href']){const v=el.getAttribute(attr);if(v?.startsWith('./'))el.setAttribute(attr,new URL(v,assetRoot).href);}const s=el.getAttribute('style');if(s)el.setAttribute('style',s.replace(/\.\/([\w-]+\.jpg)/g,(_,f)=>new URL(f,assetRoot).href));});
    const hero=doc.querySelector('main').firstElementChild;
    hero.querySelector('h1').textContent=name;const heroP=hero.querySelector('p');if(heroP)heroP.textContent=subtitle;
    hero.querySelectorAll('span').forEach(s=>{if(!s.closest('button'))s.textContent=business.category||'Descubrez';});
    hero.querySelectorAll('button').forEach((btn,i)=>{const link=doc.createElement('a');link.className=btn.className;link.href=i===0?primaryURL:'#servicios';link.textContent=i===0?primaryText:'Descubrir';btn.replaceWith(link);});
    const heroImage=safeImageURL(content.heroImage||business.heroImage);if(heroImage){const bg=hero.querySelector('[style*="background-image"]');if(bg)bg.style.backgroundImage=`linear-gradient(0deg,rgba(0,0,0,.65),transparent),url("${heroImage.replace(/["\\]/g,'')}")`;}
    doc.querySelector('title').textContent=name;head=doc.head.innerHTML;htmlClass=doc.documentElement.className;
    body=`<div class="visual-shell"><header class="visual-brand" id="inicio">${business.logo&&safeImageURL(business.logo)?`<img src="${e(safeImageURL(business.logo))}" alt="${e(name)}">`:''}<span>${e(name)}</span><a href="#contacto">Contacto</a></header>${hero.outerHTML}<div id="servicios">${sectionHTML}</div>${galleryHTML}${contact}<footer class="visual-foot">${e(name)} · ${new Date().getFullYear()}</footer></div><nav class="visual-tabs" aria-label="Navegación del negocio"><a href="#inicio">Inicio</a><a href="#servicios">Descubrir</a>${photos.length?'<a href="#galeria">Galería</a>':''}<a href="#contacto">Contacto</a></nav>`;
  }else{
    head=`<link rel="stylesheet" href="${new URL('simple.css',assetRoot)}"><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&family=Playfair+Display:wght@700&family=Cormorant+Garamond:wght@500&display=swap" rel="stylesheet">`;
    const image=safeImageURL(content.heroImage||business.heroImage)||new URL(selected.bgImage||'salamandra.jpg',assetRoot).href;
    const secondary=links.filter(l=>l.url!==primaryURL).slice(0,3);if(!secondary.length)secondary.push({text:'El negocio',url:'#contacto',action:'about'});
    body=`<main><section class="sl-container" id="inicio"><div class="sl-bg" style="background-image:url('${e(image)}')"></div><div class="sl-overlay" style="background:${selected.overlay||'rgba(0,0,0,.55)'}"></div><div class="sl-grad-top"></div><div class="sl-grad-bottom"></div><div class="sl-vignette"></div><div class="sl-content"><div class="sl-logo-area">${business.logo&&safeImageURL(business.logo)?`<img src="${e(safeImageURL(business.logo))}" alt="${e(name)}" style="width:84px;height:84px;object-fit:contain;margin-bottom:20px">`:''}<h1 class="sl-biz-name">${e(name)}</h1><p class="sl-biz-subtitle" style="color:${accent}">${e(subtitle)}</p></div><div class="sl-spacer"></div><div class="sl-buttons-area">${anchor(primaryText,primaryURL,'sl-btn-primary',firstCTA.action)}<div class="sl-btn-grid">${secondary.map(l=>anchor(l.text,l.url,'sl-btn-secondary sl-btn-label',l.action)).join('')}</div>${plan==='FREE'?'<p class="simple-brand">INNOVA AND DESIGN</p>':'<a class="simple-brand" href="#servicios">DESCUBRE MÁS ↓</a>'}</div></div></section><div class="visual-shell" id="servicios">${plan==='FREE'?'':sectionHTML+galleryHTML}${contact}<footer class="visual-foot">${e(name)}${plan==='FREE'?' · INNOVA AND DESIGN':''}</footer></div></main>`;
    head+=`<style>.sl-container{height:auto;min-height:100svh;background:#14120f}.sl-content{min-height:100svh;width:100%;max-width:520px;margin:auto;padding:0 24px}.sl-logo-area{padding-top:clamp(60px,12vh,120px)}.sl-biz-name{font-size:clamp(36px,7vw,58px);margin:0;max-width:100%}.sl-biz-subtitle{font-size:13px;line-height:1.6}.sl-spacer{min-height:180px}.sl-btn-primary{background:${accent};font-size:12px;min-height:52px}.sl-btn-label{font-size:10px}.simple-brand{display:block;color:#eee;font-size:10px;letter-spacing:.18em;text-align:center;text-decoration:none;margin:22px 0 0}.sl-buttons-area{padding-bottom:36px}.visual-shell{font-family:'DM Sans',sans-serif}@media(min-width:700px){.sl-container,.sl-content{min-height:85svh}.sl-content{max-width:620px}.sl-spacer{min-height:220px}}@media(max-height:500px){.sl-logo-area{padding-top:36px}.sl-spacer{min-height:60px}}</style>`;
  }
  const bridge=`<script>document.addEventListener('click',function(event){var link=event.target.closest('a');if(link&&link.getAttribute('href')?.startsWith('#')){event.preventDefault();document.getElementById(link.getAttribute('href').slice(1))?.scrollIntoView({behavior:'smooth'});}var a=event.target.closest('a[data-track]');if(a)parent.postMessage({type:'innova-cta',action:a.dataset.track,label:a.textContent},'*')});document.querySelectorAll('img').forEach(function(img){img.addEventListener('error',function(){img.hidden=true})});<\/script>`;
  return `<!doctype html><html lang="es" class="${htmlClass}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(name)}</title>${head}<style>${sharedCSS}body{${palette}background:${dark?'#101622':'#f8f7f5'};color:var(--text)}h1{overflow-wrap:anywhere}</style></head><body>${preview?'<div class="visual-demo-note">Vista de diseño · Imágenes de referencia del sector</div>':''}${body}${bridge}</body></html>`;
}
export async function mountLanding(frame,options){frame.srcdoc=await buildLandingDocument(options);return frame;}

