// Consolidated models. Existing source models remain available as reference material.
module.exports=function consolidate(records){
 const get=id=>records.find(r=>r.id===id);
 const strip=id=>{let s=get(id).content.split('\n\n').slice(1).join('\n\n');for(let i=0;i<4;i++)s=s.replace(/^(PRESTADOR|CLIENTE PROFESIONAL|RESPONSABLE DEL TRATAMIENTO|ENCARGADO DEL TRATAMIENTO)\n[\s\S]*?\n\n/,'');return s;};
 const head=title=>`${title}\nVersión 2.0 · 10 de octubre de 2026\nExpediente {{EXPEDIENTE}} · Fecha {{FECHA}}\n\n`;
 const parties=`INNOVA\n{{PRESTADOR_NOMBRE}}, marca INNOVANDESIGN, NIF {{NIF_PRESTADOR_VERIFICADO}}, domicilio {{PRESTADOR_DOMICILIO}}. Contacto contractual y privacidad: conta@innovandesign.com.\n\nCLIENTE\n{{CLIENTE_NOMBRE}}, NIF {{CLIENTE_NIF}}, domicilio {{CLIENTE_DOMICILIO}}, correo {{CLIENTE_EMAIL}}. Representante y facultades: {{REPRESENTANTE_Y_CAPACIDAD}}.\n\n`;
 const title='01 · Foto Fachada · Escaparates virtuales · Contratación';
 const main=head(title)+parties+`1. RESUMEN DEL PEDIDO
Servicio: Foto Fachada · Escaparates virtuales, para uso empresarial o profesional. Negocio y local: {{NEGOCIO_Y_LOCAL}}. Plan y modalidad: {{PLAN_Y_MODALIDAD}}. Periodo contratado y fecha de asignación mensual de créditos: {{PERIODO_Y_ANCLAJE}}.
Precio cerrado (base, tipo y cuota de IVA, total): {{DESGLOSE_PRECIO}}. Medio, vencimiento y estado real del pago: {{PAGO_Y_JUSTIFICANTE}}. Promoción confirmada, plaza y precio de renovación, o «No aplica»: {{PROMOCION_Y_RENOVACION}}. La firma no acredita por sí sola un cobro.
Funciones incluidas, herramientas gratuitas realmente disponibles y extras aceptados: {{ALCANCE_Y_DISPONIBILIDAD}}. Materiales, permisos y restricciones de licencia: {{MATERIALES_Y_PERMISOS}}. Formato y acabado del cartel, lugar y fecha prevista de entrega: {{DATOS_ENTREGA}}. Condiciones adicionales o «Ninguna»: {{CONDICIONES_PARTICULARES}}.

2. SERVICIO Y PLANES
INNOVA prepara, aloja y permite gestionar la presencia digital del negocio mediante una página y un QR. Cada contratación cubre un local; varias sucursales requieren Enterprise y presupuesto específico. Una campaña activa es una campaña publicada y accesible. Free admite una, Pro cinco y Business diez simultáneas; este límite es independiente de los créditos IA.
Free incluye contacto básico y totales de QR y clics. Pro añade servicios, oferta, horarios, mapa, redes y desglose por campaña y fechas. Business añade galería, navegación, animaciones, comparativas y exportación. Los clics son interacciones, no ventas ni personas únicas garantizadas. Las funciones aún desactivadas se identifican en el pedido y no se consideran entregadas. No se garantiza un resultado de ventas, contactos o posicionamiento.
El cliente aporta datos y materiales correctos y con permiso. Autoriza su adaptación y uso para el servicio, sin ceder su propiedad ni autorizar usos para otros clientes. Revisa los datos sugeridos por IA y aprueba la versión final antes de publicarla. La contratación no aprueba anticipadamente un diseño. Los casos de éxito, publicidad o comunicaciones promocionales requieren una autorización separada cuando corresponda y pueden rechazarse sin perder el servicio.

3. PRECIO, PROMOCIÓN Y DURACIÓN
Tarifas ordinarias, más IVA: Pro 20 euros/mes o 200 euros/año; Business 38 euros/mes o 380 euros/año. El pedido concreta el importe aplicable. Los primeros 50 clientes anuales de pago con plaza confirmada acceden a precio fijo de 100 euros/año Pro o 190 euros/año Business, más IVA, mientras mantengan continuidad anual. No es un descuento variable sobre futuras tarifas. El cambio entre Pro y Business conserva la promoción correspondiente si continúa la anualidad. Pasar a mensual, cancelar o agotar la gracia sin pagar la pierde; una nueva contratación no la recupera.
No hay permanencia adicional al periodo abonado. Se puede pedir la baja en cualquier momento, efectiva al terminar ese periodo. La baja voluntaria anticipada no devuelve la parte no consumida, salvo devolución debida legalmente o por incumplimiento. La renovación requiere pago y comunicación previa de importe y vencimiento. Se admite transferencia, Bizum profesional y efectivo dentro del límite legal; un recibo no sustituye la factura. No se autoriza un adeudo automático por firmar.
La subida de plan cobra la diferencia proporcional a los días pendientes, mostrando el cálculo antes de aceptarlo. La bajada se aplica al final del periodo. Al pasar de mensual a anual se descuenta el valor no consumido del mes y comienza un año nuevo. El cliente elige las campañas que conserva si disminuye su límite. Los extras se presupuestan y aceptan antes de ejecutarse.

4. CRÉDITOS E IA
La generación inicial incluida no descuenta créditos. El control de lanzamiento permite una generación inicial en Free durante la vida de la cuenta y hasta cinco en Pro o diez en Business por periodo mensual de contratación; al agotarlo se informa y puede continuarse manualmente, sin convertirlo en un cargo automático. Editar manualmente, sustituir materiales o reactivar sin ejecutar IA cuesta cero.
Free recibe cero créditos periódicos. Pro y Business reciben 1.000 cada mes desde la contratación y acumulan lo no consumido. Pro: regeneración conjunta de diseño y marketing, 200 créditos; operación individual de diseño, marketing o análisis de fachada, 100. Business: conjunta, 100; individual, 50. Enterprise se define en sus condiciones particulares. Los créditos son unidades de uso, distintas de los tokens del proveedor; no son dinero depositado ni se transfieren entre cuentas.
Se muestra el coste antes de confirmar. Una operación válida completada puede consumir créditos aunque se descarte; un fallo técnico, respuesta inválida o generación fallida devuelve la reserva. Las peticiones repetidas con la misma referencia no duplican el cargo. Regenerar el diseño conserva el contenido aportado y cambia su presentación; aceptar y publicar son decisiones separadas.
Recargas, más IVA: 200 créditos por 5 euros; 600 por 12 euros; 1.400 por 25 euros. Se activan tras verificar el pago. Las herramientas gratuitas disponibles se detallan en el pedido: pueden tener colas o límites de frecuencia y no pasan automáticamente a servicios de pago. La edición o generación de logo y retirada de fondo no se presupone activa. Los cambios de tarifa se comunican antes de aplicarlos, sin modificar operaciones ya confirmadas. El saldo no se canjea por efectivo, salvo devolución legalmente debida.

5. ENTREGA, SOPORTE Y DOMINIO
Un plan de pago, incluso de un mes, incluye dos rondas de revisión inicial y un cartel hasta A3, papel 90 g, brillo o mate, entregado en mano. El plazo es de 24–48 horas laborables desde pago recibido, cartel generado y campaña activa; lunes a viernes, excluidos festivos aplicables en Benidorm. La falta de datos o aprobación desplaza la fecha y se comunica. Nuevas impresiones, envíos y trabajos fuera de alcance se presupuestan aparte.
Soporte por teléfono y WhatsApp de lunes a viernes, 09:00–20:00, hora peninsular; objetivo de primera respuesta una hora dentro de horario, sin equivaler a resolución garantizada. Javi atiende la entrega técnica y Andrey coordina sustituciones.
Business incluye un dominio disponible .com o .es y sus renovaciones mientras continúe el plan. Datos acordados (nombre, titular, registrador, contacto, fecha de alta/renovación y vencimiento), o «No aplica»: {{DOMINIO_Y_REGISTRO}}. Si todavía no está registrado, se indica «Pendiente de alta» y se confirma después en el expediente, sin inventar disponibilidad. Al cancelar Business mensual se conserva hasta el vencimiento del registro ya pagado sin cargo adicional. La salida se coordina con el titular y el registrador; no se retienen credenciales para impedirla. Correo corporativo y gestiones extraordinarias de transferencia no se incluyen salvo acuerdo. No se promete renovar tras finalizar el plan.

6. GRACIA, BAJA Y CONSERVACIÓN
Ante impago de renovación, sin baja voluntaria previa, se concede un mes de gracia: siguen las publicaciones, la asignación mensual y el uso del saldo; no se compran recargas. Si se paga, el periodo continúa desde el vencimiento original. Agotada la gracia, pasa a Free, se bloquea lo que exceda ese plan y se congela el saldo. La baja voluntaria no añade un mes gratuito.
Los contenidos bloqueados se conservan para recuperación durante tres años desde el fin del plan de pago, salvo supresión que proceda; el saldo se recupera al volver a contratar durante ese plazo. Puede pedirse copia del contenido propio antes de eliminarlo. Al finalizar la conservación podrá eliminarse previa comunicación al correo de la cuenta. Contratos y facturas tienen plazos legales independientes. Estas condiciones no anulan derechos de protección de datos.

7. INCIDENCIAS Y RESPONSABILIDAD
Cada parte responde de sus obligaciones y daños imputables conforme a la ley. INNOVA mantiene controles de acceso, separación de cuentas y registro de operaciones, comunica incidencias relevantes y aplica medidas razonables de recuperación. El cliente protege sus credenciales y avisa de accesos indebidos. Un fallo de un proveedor no exonera automáticamente a INNOVA. No se excluye responsabilidad por dolo ni otra legalmente indisponible. Ante incumplimiento relevante puede solicitarse subsanación y ejercerse los remedios legales.
Avisos y reclamaciones: conta@innovandesign.com y correo del cliente. INNOVA acusará recibo y dará respuesta motivada. Rige el derecho español y europeo aplicable y los tribunales legalmente competentes, sin renuncia a fueros imperativos.

8. PRIVACIDAD
`+strip('privacidad').replace(/RESPONSABLE Y CONTACTO[\s\S]*?(?=1\. INFORMACIÓN)/,'El prestador identificado al inicio es responsable de la gestión comercial, contractual y de cuenta. Contacto para derechos: conta@innovandesign.com.\n\n').replaceAll('{{ACLARACIONES_O_NINGUNA}}','{{CONDICIONES_PARTICULARES}}')+`

9. TRATAMIENTO DE DATOS POR CUENTA DEL CLIENTE
Aplicabilidad y motivo: {{APLICA_ENCARGO_Y_MOTIVO}}. Cuando INNOVA trate datos por cuenta del cliente, este actúa como responsable e INNOVA como encargado. Los siguientes términos son parte de este documento, sin firma separada. Si no corresponde, debe justificarse y marcar sus datos «No aplica». Si corresponde, el inventario debe completarse antes de tratar datos.

`+strip('encargo').replace(/8\. ACEPTACIÓN[\s\S]*$/,'Los cambios de estas instrucciones requieren constancia escrita.')+`

10. ACEPTACIÓN ÚNICA
La firma comprende el pedido, las condiciones y los apartados aplicables de esta versión. El firmante ha podido leerlos, completar sus datos y pedir aclaraciones. Parte que firma: {{PARTE_QUE_FIRMA}}; aceptación de la otra parte acreditada en {{EVIDENCIA_ACEPTACION_OTRA_PARTE}}. La firma manuscrita se vincula a contenido, versión y fecha; no se presenta como firma cualificada. Se entrega una copia íntegra.
La firma no declara pagado, aprobado o entregado lo que todavía no lo esté. Esos hechos y cualquier cambio o baja se registran después, con la misma referencia de expediente. Una versión firmada no se modifica; las rectificaciones se documentan aparte. Este documento no incorpora los acuerdos internos de personal de INNOVA.`;
 Object.assign(get('documento-unico'),{title,content:main,category:'servicios'});
 const managementTitle='02 · Gestión del expediente · Foto Fachada';
 records.unshift({id:'gestion-expediente',title:managementTitle,category:'clientes',content:head(managementTitle)+parties+`1. OPERACIÓN Y REFERENCIA
Contrato o documento previo relacionado: {{REFERENCIA_CONTRATO}}. Tipo de gestión: {{TIPO_GESTION}}. Se registra una sola operación por copia: aprobación de diseño, entrega, recibo de pago, cambio de plan o baja. La firma solo alcanza el tipo seleccionado, nunca los demás.

2. DETALLE DE LA OPERACIÓN
{{DETALLE_OPERACION}}

3. ALCANCE SEGÚN EL TIPO
Aprobación de diseño: el detalle identifica versión, enlace o archivo, datos y oferta revisados, restricciones y reservas. Solo autoriza publicar la versión identificada; no autoriza publicidad como caso de éxito ni cambios sustanciales posteriores.
Entrega: el detalle recoge elementos y accesos entregados, lugar, fecha, cartel, pruebas de QR realmente realizadas y reservas con responsable y plazo. La recepción no acredita pruebas no realizadas ni implica renunciar a reclamar defectos.
Recibo de pago: el detalle debe indicar número de recibo, quién entrega y recibe, concepto, base, IVA y total, importe recibido, medio, fecha, justificante y saldo pendiente. Solo lo confirma quien puede acreditar la recepción. No sustituye la factura ni permite superar el límite legal de efectivo.
Cambio de plan: el detalle indica plan/modalidad anterior y nueva, fecha efectiva, periodo pendiente, cálculo de diferencia, impuestos y total, campañas que se conservan y efecto sobre promoción, créditos y dominio. No se aplica sin aceptación del importe y alcance. Las bajadas se aplican al fin del periodo salvo acuerdo válido distinto.
Baja: el detalle identifica fecha de solicitud y de fin del periodo pagado, paso a Free, campañas conservadas, saldo congelado, recuperación de contenido y estado/salida del dominio. La baja voluntaria no añade gracia. Los tres años de conservación del contenido no sustituyen plazos legales de contratos y facturas ni impiden una supresión procedente.

4. CONFORMIDAD LIMITADA
Decisión, reservas y siguientes acciones: {{DECISION_Y_RESERVAS}}. Parte que firma y facultad para confirmar la operación: {{PARTE_QUE_FIRMA}}. Aceptación de la otra parte cuando se requiera: {{EVIDENCIA_ACEPTACION_OTRA_PARTE}}. Una firma no inventa un pago, entrega o consentimiento; no altera la versión firmada del contrato. Se conserva copia con la misma referencia de expediente.`});
 const internalTitle='04 · Organización y control · Foto Fachada';
 records.unshift({id:'organizacion-control',title:internalTitle,category:'organizacion',content:head(internalTitle)+strip('procedimiento').replaceAll('Escaparates digitales','Foto Fachada · Escaparates virtuales')+`\n\nREVISIÓN Y AUTORIZACIÓN DE USO\nEste apartado recoge la revisión real del procedimiento y de los modelos del producto. Revisor y función: {{REVISOR_NOMBRE_Y_FUNCION}}. Modelos y versiones revisadas: {{LISTA_VERSIONES_REVISADAS}}.\nResultado conjunto de identidad fiscal, precios y límites, proveedores y garantías, dominio, firma y recepción de copias: {{RESULTADO_REVISION}}. Deben identificarse los puntos no comprobados, las pruebas realizadas y sus evidencias.\nDecisión (aprobado, aprobado con reservas o no aprobado) y usos autorizados: {{DECISION_Y_ALCANCE}}. Reservas, acciones, responsables y fechas: {{ACCIONES_Y_RESERVAS}}. La firma expresa esa decisión concreta; no certifica un dictamen profesional que no se haya emitido, no firma por el cliente y no corrige por sí sola datos fiscales pendientes.`});
 return records;
};
