'use strict';
const $=id=>document.getElementById(id),api='/erp/api/documents.php';
const scope=new URLSearchParams(location.search).get('service')||'';
let docs=[],current=null,busy=false,signedStroke=false,drawing=false,copySource=null;
const notice=s=>{$('notice').textContent=s;};
const missing=s=>[...new Set([...String(s).matchAll(/\{\{([A-Z0-9_]+)\}\}/g)].map(m=>m[1]))];
async function request(url,body){const r=await fetch(url,{credentials:'same-origin',cache:'no-store',...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});let d;try{d=await r.json();}catch{throw Error('No se recibió una respuesta válida. Comprueba el expediente antes de repetir.');}if(!r.ok)throw Error(d.error||'No se pudo completar la operación.');return d;}
async function load(){try{const r=await request(api+'?service='+encodeURIComponent(scope));docs=r.documents;render();}catch(e){notice(e.message);}}
function render(){const q=$('search').value.toLowerCase(),area=$('filter').value,collection=$('collection').value;$('list').replaceChildren();const matches=docs.filter(d=>(collection==='all'||(d.entity_type==='plantilla')===(collection==='templates'))&&(!area||area===d.category)&&[d.title,d.service_code,d.entity_id].join(' ').toLowerCase().includes(q)).sort((a,b)=>collection==='templates'?a.title.localeCompare(b.title,'es'):0);for(const d of matches){const card=document.createElement('article'),title=document.createElement('h2'),meta=document.createElement('p'),button=document.createElement('button');title.textContent=d.title;meta.textContent=d.entity_type==='plantilla'?'Modelo completo · Crear una copia para cada expediente':`${d.category} · ${d.service_code||'General'} · ${label(d.status)} · v${d.revision}`;button.textContent=d.entity_type==='plantilla'?'Leer documento completo':'Abrir documento';button.onclick=()=>open(d.id);card.append(title,meta,button);$('list').append(card);}if(!matches.length){const p=document.createElement('p');p.textContent='No hay documentos que coincidan con este filtro.';$('list').append(p);}}
function label(s){return {draft:'Preparación',reviewed:'Conformidad registrada',signed:'Firmado',pending:'Pendiente',sending:'Envío iniciado; comprobar antes de reintentar',accepted:'Aceptado por el servidor de correo',failed:'Error de envío'}[s]||s;}
function readText(){const reader=$('reader');reader.replaceChildren();const brand=document.createElement('div');brand.className='document-brand';const mark=document.createElement('span');mark.className='brand-mark';mark.textContent='I';const name=document.createElement('span');name.textContent='INNOVA & DESIGN';brand.append(mark,name);reader.append(brand);const title=document.createElement('h1');title.textContent=$('title').value;reader.append(title);for(const block of $('content').value.split(/\n\s*\n/)){const section=document.createElement('section'),lines=block.split('\n');if(lines.length>1&&/^(?:\d+\.|[A-ZÁÉÍÓÚÑ][A-ZÁÉÍÓÚÑ ,·0-9/-]+$)/.test(lines[0])){const h=document.createElement('h2');h.textContent=lines.shift();section.append(h);}const p=document.createElement('p');p.textContent=lines.join('\n');section.append(p);reader.append(section);}const fields=missing($('content').value);$('completion').textContent=fields.length?`${fields.length} datos por completar. Usa «Preparar copia para firma» para rellenarlos.`:'Texto sin campos de plantilla pendientes. Revisa los datos y el alcance antes de dar conformidad.';}
async function open(id){try{current=id?await request(api+'?id='+encodeURIComponent(id)):null;show();$('editor').showModal();}catch(e){notice(e.message);}}
function show(){const d=current||{},locked=d.status==='signed',template=d.entity_type==='plantilla';$('title').value=d.title||'';$('content').value=d.content||'';$('category').value=d.category||'servicios';$('service').value=d.service_code||scope;$('entityType').value=d.entity_type||'';$('entityId').value=d.entity_id||'';for(const id of ['title','content'])$(id).disabled=locked||template;for(const id of ['category','service','entityType','entityId'])$(id).disabled=Boolean(current);$('save').hidden=locked||template;$('review').hidden=!current||locked||template||d.status==='reviewed';$('prepare-sign').hidden=d.status!=='reviewed'||template;$('create-copy').hidden=!current;$('create-copy').textContent=template?'Preparar copia para firma':'Crear una nueva copia';$('sign-panel').hidden=true;$('document-state').textContent=template?'Modelo completo · El original se conserva':current?`${label(d.status)} · Versión ${d.revision}`:'Nuevo documento';$('edit-details').open=!current;$('edit-details').hidden=template;$('integrity').textContent=d.signature_hash?'SHA-256: '+d.signature_hash:'';$('print').hidden=locked;$('download').hidden=!locked;$('download').href=api+'?id='+encodeURIComponent(d.id||'')+'&download=1';$('send').hidden=!locked||!(d.deliveries||[]).some(x=>['pending','failed'].includes(x.state));for(const [id,rows] of [['history',(d.versions||[]).map(v=>`v${v.revision} · ${v.actor} · ${v.created_at}`)],['deliveries',(d.deliveries||[]).map(v=>`${v.recipient}: ${label(v.state)}`)]]){$(id).replaceChildren();for(const text of rows){const li=document.createElement('li');li.textContent=text;$(id).append(li);}}readText();}
async function act(action,extra={}){if(busy)return;busy=true;for(const b of $('document-form').querySelectorAll('button'))b.disabled=true;try{const body={action,...(current?{id:current.id,revision:current.revision}:{}),...extra};const r=await request(api,body);current=await request(api+'?id='+encodeURIComponent((r.document||r).id));show();await load();notice(action==='sign'?'Documento firmado y guardado. Comprueba el estado de cada envío.':'Cambios guardados.');}catch(e){notice(e.message);if(current?.id){try{const fresh=await request(api+'?id='+encodeURIComponent(current.id));if(fresh.status==='signed'){current=fresh;show();}}catch{}}$('completion').textContent=e.message;}finally{busy=false;for(const b of $('document-form').querySelectorAll('button'))b.disabled=false;}}
$('document-form').onsubmit=e=>{e.preventDefault();act(current?'update':'create',{title:$('title').value,content:$('content').value,category:$('category').value,serviceCode:$('service').value,entityType:$('entityType').value,entityId:$('entityId').value});};
const dirty=()=>current?($('title').value!==current.title||$('content').value!==current.content):Boolean($('title').value||$('content').value);
function ready(){if(dirty()){$('completion').textContent='Guarda los cambios antes de continuar.';return false;}if(missing($('content').value).length){$('completion').textContent='Completa todos los campos antes de dar conformidad o firmar.';return false;}return true;}
$('review').onclick=()=>{if(ready())act('review');};
$('prepare-sign').onclick=()=>{if(!ready())return;$('sign-panel').hidden=false;$('signer').value='';$('recipients').value='';$('consent').checked=false;clearSignature();};
const canvas=$('signature'),ctx=canvas.getContext('2d');ctx.lineWidth=2.5;ctx.lineCap='round';ctx.strokeStyle='#111';
function point(e){const r=canvas.getBoundingClientRect();return [(e.clientX-r.left)*canvas.width/r.width,(e.clientY-r.top)*canvas.height/r.height];}
canvas.onpointerdown=e=>{drawing=true;canvas.setPointerCapture(e.pointerId);ctx.beginPath();ctx.moveTo(...point(e));};canvas.onpointermove=e=>{if(!drawing)return;ctx.lineTo(...point(e));ctx.stroke();signedStroke=true;};canvas.onpointerup=canvas.onpointercancel=()=>{drawing=false;};
function clearSignature(){ctx.clearRect(0,0,canvas.width,canvas.height);signedStroke=false;}$('clear').onclick=clearSignature;
$('sign').onclick=()=>{if(!signedStroke||!$('consent').checked||$('signer').value.trim().length<2){$('completion').textContent='Escribe el nombre, dibuja la firma y acepta el documento.';return;}if(!ready())return;const recipients=$('recipients').value.split(',').map(s=>s.trim()).filter(Boolean);act('sign',{signer:$('signer').value.trim(),signature:canvas.toDataURL('image/png'),consent:true,recipients});};
$('create-copy').onclick=()=>{copySource=current;$('fields').replaceChildren();$('builder-error').textContent='';$('builder-title').textContent=current.title;$('copy-service').value=scope||current.service_code||'';for(const key of missing(current.content)){const label=document.createElement('label'),input=document.createElement('textarea');label.textContent=key.replaceAll('_',' ').toLowerCase();input.name=key;input.required=true;input.maxLength=8000;input.rows=2;if(key==='FECHA')input.value=new Date().toLocaleDateString('es-ES');label.append(input);$('fields').append(label);}$('builder').showModal();};
$('builder-form').onsubmit=async e=>{e.preventDefault();if(busy)return;const values=Object.fromEntries(new FormData($('builder-form')));const content=copySource.content.replace(/\{\{([A-Z0-9_]+)\}\}/g,(_,key)=>String(values[key]||'').trim());if(missing(content).length||Object.values(values).some(v=>!String(v).trim())){$('builder-error').textContent='Completa todos los datos.';return;}if(content.length>100000){$('builder-error').textContent='El documento excede el tamaño permitido.';return;}busy=true;$('builder-form').querySelector('button[type=submit]').disabled=true;try{const ref=String(values.EXPEDIENTE||'Copia').slice(0,80);const d=await request(api,{action:'create',title:(copySource.title+' · '+ref).slice(0,200),category:copySource.category,serviceCode:$('copy-service').value,entityType:copySource.category==='colaboradores'?'colaborador':copySource.category==='organizacion'?'departamento':'cliente',entityId:ref,content});current=await request(api+'?id='+encodeURIComponent(d.id));$('builder').close();show();$('collection').value='records';await load();notice('Copia completa creada. Lee el documento antes de dar conformidad y firmar.');}catch(err){$('builder-error').textContent=err.message;}finally{busy=false;$('builder-form').querySelector('button[type=submit]').disabled=false;}};
$('builder-close').onclick=()=>{if(!busy)$('builder').close();};$('builder').addEventListener('cancel',e=>{if(busy)e.preventDefault();});
$('send').onclick=()=>act('send');$('close').onclick=()=>{if(!busy&&(!dirty()||confirm('¿Cerrar sin guardar los cambios?')))$('editor').close();};$('editor').addEventListener('cancel',e=>{if(busy||dirty())e.preventDefault();});$('new').onclick=()=>open(null);$('refresh').onclick=load;$('search').oninput=render;$('filter').onchange=render;$('collection').onchange=render;$('content').oninput=$('title').oninput=readText;$('print').onclick=()=>window.print();$('scope').textContent=scope?'Documentación del servicio '+scope+' · Modelos generales disponibles para preparar copias':'Biblioteca de documentos completos y expedientes';load();
