'use strict';
const $=id=>document.getElementById(id),api='/erp/api/documents.php';
const scope=new URLSearchParams(location.search).get('service')||'';
let docs=[],current=null,busy=false,signedStroke=false,drawing=false;
const notice=s=>{$('notice').textContent=s;};
async function request(url,body){const r=await fetch(url,{credentials:'same-origin',cache:'no-store',...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(d.error||'No se pudo completar la operación.');return d;}
async function load(){try{const r=await request(api+'?service='+encodeURIComponent(scope));docs=r.documents;render();}catch(e){notice(e.message);}}
function render(){const q=$('search').value.toLowerCase(),area=$('filter').value;$('list').replaceChildren();const matches=docs.filter(d=>(!area||area===d.category)&&[d.title,d.service_code,d.entity_id].join(' ').toLowerCase().includes(q));for(const d of matches){const card=document.createElement('article'),title=document.createElement('h2'),meta=document.createElement('p'),button=document.createElement('button');title.textContent=d.title;meta.textContent=`${d.category} · ${d.service_code||'General'} · ${label(d.status)} · v${d.revision}`;button.textContent='Abrir documento';button.onclick=()=>open(d.id);card.append(title,meta,button);$('list').append(card);}if(!matches.length){const p=document.createElement('p');p.textContent='No hay documentos que coincidan con este filtro.';$('list').append(p);}}
function label(s){return {draft:'Borrador',reviewed:'Revisado',signed:'Firmado',pending:'Pendiente',sending:'Envío iniciado; comprobar antes de reintentar',accepted:'Aceptado por el servidor de correo',failed:'Error de envío'}[s]||s;}
async function open(id){try{current=id?await request(api+'?id='+encodeURIComponent(id)):null;show();$('editor').showModal();}catch(e){notice(e.message);}}
function show(){const d=current||{},locked=d.status==='signed';$('title').value=d.title||'';$('content').value=d.content||'';$('category').value=d.category||'servicios';$('service').value=d.service_code||scope;$('entityType').value=d.entity_type||'';$('entityId').value=d.entity_id||'';for(const id of ['title','content'])$(id).disabled=locked;for(const id of ['category','service','entityType','entityId'])$(id).disabled=Boolean(current);$('save').hidden=locked;$('review').hidden=!current||locked||d.status==='reviewed';$('prepare-sign').hidden=d.status!=='reviewed';$('sign-panel').hidden=true;$('document-state').textContent=current?`${label(d.status)} · Versión ${d.revision}`:'Nuevo borrador';$('integrity').textContent=d.signature_hash?'SHA-256: '+d.signature_hash:'';$('download').hidden=!locked;$('download').href=api+'?id='+encodeURIComponent(d.id||'')+'&download=1';$('send').hidden=!locked||!(d.deliveries||[]).some(x=>['pending','failed'].includes(x.state));for(const [id,rows] of [['history',(d.versions||[]).map(v=>`v${v.revision} · ${v.actor} · ${v.created_at}`)],['deliveries',(d.deliveries||[]).map(v=>`${v.recipient}: ${label(v.state)}`)]]){$(id).replaceChildren();for(const text of rows){const li=document.createElement('li');li.textContent=text;$(id).append(li);}}}
async function act(action,extra={}){if(busy)return;busy=true;for(const b of $('document-form').querySelectorAll('button'))b.disabled=true;try{const body={action,...(current?{id:current.id,revision:current.revision}:{}),...extra};const r=await request(api,body);current=await request(api+'?id='+encodeURIComponent((r.document||r).id));show();await load();notice(action==='sign'?'Documento firmado y guardado. Comprueba el estado de cada envío.':'Cambios guardados.');}catch(e){notice(e.message);alert(e.message);}finally{busy=false;for(const b of $('document-form').querySelectorAll('button'))b.disabled=false;}}
$('document-form').onsubmit=e=>{e.preventDefault();act(current?'update':'create',{title:$('title').value,content:$('content').value,category:$('category').value,serviceCode:$('service').value,entityType:$('entityType').value,entityId:$('entityId').value});};
const dirty=()=>current&&($('title').value!==current.title||$('content').value!==current.content);
$('review').onclick=()=>{if(dirty()){alert('Guarda los cambios antes de revisar.');return;}if(confirm('¿Confirmas que has revisado este documento y está listo para firmar?'))act('review');};
$('prepare-sign').onclick=()=>{if(dirty()){alert('Guarda y revisa la nueva versión antes de firmar.');return;}$('sign-panel').hidden=false;$('signer').value='';$('consent').checked=false;clearSignature();};
const canvas=$('signature'),ctx=canvas.getContext('2d');ctx.lineWidth=2.5;ctx.lineCap='round';ctx.strokeStyle='#111';
function point(e){const r=canvas.getBoundingClientRect();return [(e.clientX-r.left)*canvas.width/r.width,(e.clientY-r.top)*canvas.height/r.height];}
canvas.onpointerdown=e=>{drawing=true;canvas.setPointerCapture(e.pointerId);ctx.beginPath();ctx.moveTo(...point(e));};canvas.onpointermove=e=>{if(!drawing)return;ctx.lineTo(...point(e));ctx.stroke();signedStroke=true;};canvas.onpointerup=canvas.onpointercancel=()=>{drawing=false;};
function clearSignature(){ctx.clearRect(0,0,canvas.width,canvas.height);signedStroke=false;}$('clear').onclick=clearSignature;
$('sign').onclick=()=>{if(!signedStroke||!$('consent').checked||$('signer').value.trim().length<2){alert('Escribe el nombre, dibuja la firma y acepta el documento.');return;}if(dirty()){alert('El documento cambió. Guárdalo y revísalo antes de firmar.');return;}const recipients=$('recipients').value.split(',').map(s=>s.trim()).filter(Boolean);act('sign',{signer:$('signer').value.trim(),signature:canvas.toDataURL('image/png'),consent:true,recipients});};
$('send').onclick=()=>act('send');$('close').onclick=()=>{if(!busy&&(!dirty()||confirm('¿Cerrar sin guardar los cambios?')))$('editor').close();};$('editor').addEventListener('cancel',e=>{if(busy||dirty())e.preventDefault();});$('new').onclick=()=>open(null);$('refresh').onclick=load;$('search').oninput=render;$('filter').onchange=render;$('scope').textContent=scope?'Documentación del servicio '+scope:'Archivo central de documentación';load();
