'use strict';
const $=id=>document.getElementById(id),api='/erp/api/documents.php';
const scope=new URLSearchParams(location.search).get('service')||'';
let docs=[],current=null,busy=false,signedStroke=false,drawing=false,copySource=null;
const notice=s=>{$('notice').textContent=s;};
const missing=s=>[...new Set([...String(s).matchAll(/\{\{([A-Z0-9_]+)\}\}/g)].map(m=>m[1]))];
async function request(url,body){const r=await fetch(url,{credentials:'same-origin',cache:'no-store',...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});let d;try{d=await r.json();}catch{throw Error('No se recibió una respuesta válida. Comprueba el expediente antes de repetir.');}if(!r.ok)throw Error(d.error||'No se pudo completar la operación.');return d;}
async function load(){try{const r=await request(api+'?service='+encodeURIComponent(scope));docs=r.documents;render();}catch(e){notice(e.message);}}
const areaNames={servicios:'Servicios',clientes:'Clientes',legal:'Legal',organizacion:'Organización',colaboradores:'Colaboradores',proyectos:'Proyectos',facturacion:'Facturación'};
const viewNames={templates:'Plantillas',records:'Expedientes',reviewed:'Pendientes de firma',signed:'Firmados',all:'Todo el archivo'};
function icon(name){const i=document.createElement('img');i.src=DOCUMENT_ICONS[name]||DOCUMENT_ICONS['file-earmark-text'];i.alt='';i.className='icon';return i;}
function cleanTitle(t){return t.replace(/^\d+\s*·\s*/,'');}
function render(){const q=$('search').value.toLocaleLowerCase('es'),area=$('filter').value,collection=$('collection').value;$('list').replaceChildren();
 const matches=docs.filter(d=>(collection==='all'||(collection==='templates'?d.entity_type==='plantilla':collection==='records'?d.entity_type!=='plantilla':d.entity_type!=='plantilla'&&d.status===collection))&&(!area||area===d.category)&&[d.title,d.service_code,d.entity_id].join(' ').toLocaleLowerCase('es').includes(q)).sort((a,b)=>$('sort').value==='recent'?new Date(b.updated_at)-new Date(a.updated_at):a.title.localeCompare(b.title,'es'));
 $('view-title').textContent=area?areaNames[area]:viewNames[collection];$('scope').textContent=scope?'Documentación del servicio '+scope:collection==='templates'?'Modelos completos para preparar tus expedientes.':'Consulta, revisa y firma los documentos de tus expedientes.';$('result-count').textContent=matches.length+' documentos';
 document.querySelectorAll('[data-view]').forEach(b=>{if(b.dataset.view===collection&&!area)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});document.querySelectorAll('[data-area]').forEach(b=>{if(b.dataset.area===area)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});
 for(const d of matches){const row=document.createElement('button');row.type='button';row.className='document-row'+(current?.id===d.id?' selected':'');row.setAttribute('aria-label','Abrir '+cleanTitle(d.title));const first=document.createElement('span');first.className='row-name';first.append(icon('file-earmark-text'));const text=document.createElement('span'),title=document.createElement('strong'),meta=document.createElement('small');title.textContent=cleanTitle(d.title);meta.textContent=d.entity_type==='plantilla'?'Modelo completo':label(d.status)+' · '+(d.entity_id||'General')+' · v'+d.revision;text.append(title,meta);first.append(text);const areaEl=document.createElement('span');areaEl.className='area-badge area-'+d.category;areaEl.textContent=areaNames[d.category]||d.category;const date=document.createElement('time');date.dateTime=d.updated_at;date.textContent=new Intl.DateTimeFormat('es-ES',{day:'numeric',month:'short',year:'numeric'}).format(new Date(d.updated_at));row.append(first,areaEl,date);row.onclick=()=>open(d.id);$('list').append(row);}
 if(!matches.length){const p=document.createElement('p');p.className='empty-state';p.textContent=q||area?'No encontramos documentos con estos filtros. Cambia la búsqueda o el área.':'Todavía no hay documentos en esta sección. Puedes preparar una copia desde Plantillas.';$('list').append(p);}}
function selectTab(tab){$('sign-panel').hidden=true;for(const name of ['read','info','activity'])$(name+'-pane').hidden=name!==tab;document.querySelectorAll('[data-tab]').forEach(b=>(b.setAttribute('aria-selected',String(b.dataset.tab===tab)),b.tabIndex=b.dataset.tab===tab?0:-1));if(tab==='info')$('edit-details').open=true;}
function label(s){return {draft:'Preparación',reviewed:'Conformidad registrada',signed:'Firmado',pending:'Pendiente',sending:'Envío iniciado; comprobar antes de reintentar',accepted:'Aceptado por el servidor de correo',failed:'Error de envío'}[s]||s;}
function readText(){const reader=$('reader');reader.replaceChildren();const brand=document.createElement('div');brand.className='document-brand';const mark=document.createElement('span');mark.className='brand-mark';mark.textContent='I';const name=document.createElement('span');name.textContent='INNOVA & DESIGN';brand.append(mark,name);reader.append(brand);const title=document.createElement('h1');title.textContent=$('title').value;reader.append(title);for(const block of $('content').value.split(/\n\s*\n/)){const section=document.createElement('section'),lines=block.split('\n');if(lines.length>1&&/^(?:\d+\.|[A-ZÁÉÍÓÚÑ][A-ZÁÉÍÓÚÑ ,·0-9/-]+$)/.test(lines[0])){const h=document.createElement('h2');h.textContent=lines.shift();section.append(h);}const p=document.createElement('p');p.textContent=lines.join('\n');section.append(p);reader.append(section);}const fields=missing($('content').value);$('completion').textContent=fields.length?`${fields.length} datos por completar. Usa «Preparar copia para firma» para rellenarlos.`:'Texto sin campos de plantilla pendientes. Revisa los datos y el alcance antes de dar conformidad.';}
async function open(id){if(busy)return;if($('editor').open&&dirty()&&!confirm('¿Descartar los cambios sin guardar?'))return;try{current=id?await request(api+'?id='+encodeURIComponent(id)):null;show();if(!$('editor').open)$('editor').show();document.body.classList.add('reader-open');$('close').focus();render();}catch(e){notice(e.message);}}
function show(){const d=current||{},locked=d.status==='signed',template=d.entity_type==='plantilla';$('title').value=d.title||'';$('content').value=d.content||'';$('category').value=d.category||'servicios';$('service').value=d.service_code||scope;$('entityType').value=d.entity_type||'';$('entityId').value=d.entity_id||'';for(const id of ['title','content'])$(id).disabled=locked||template;for(const id of ['category','service','entityType','entityId'])$(id).disabled=Boolean(current);$('save').hidden=locked||template;$('review').hidden=!current||locked||template||d.status==='reviewed';$('prepare-sign').hidden=d.status!=='reviewed'||template;$('create-copy').hidden=!current;$('create-copy').textContent=template?'Preparar copia para firma':'Crear una nueva copia';$('sign-panel').hidden=true;$('document-state').textContent=template?'Modelo completo · El original se conserva':current?`${label(d.status)} · Versión ${d.revision}`:'Nuevo documento';$('edit-details').open=!current;$('edit-details').hidden=false;$('integrity').textContent=d.signature_hash?'SHA-256: '+d.signature_hash:'';$('print').hidden=locked;$('download').hidden=!locked;$('download').href=api+'?id='+encodeURIComponent(d.id||'')+'&download=1';$('send').hidden=!locked||!(d.deliveries||[]).some(x=>['pending','failed'].includes(x.state));for(const [id,rows] of [['history',(d.versions||[]).map(v=>`v${v.revision} · ${v.actor} · ${v.created_at}`)],['deliveries',(d.deliveries||[]).map(v=>`${v.recipient}: ${label(v.state)}`)]]){$(id).replaceChildren();for(const text of rows){const li=document.createElement('li');li.textContent=text;$(id).append(li);}}readText();$('editor-title').textContent=cleanTitle(d.title||'Nuevo documento');selectTab(current?'read':'info');}
async function act(action,extra={}){if(busy)return;busy=true;for(const b of $('document-form').querySelectorAll('button'))b.disabled=true;try{const body={action,...(current?{id:current.id,revision:current.revision}:{}),...extra};const r=await request(api,body);current=await request(api+'?id='+encodeURIComponent((r.document||r).id));show();await load();notice(action==='sign'?'Documento firmado y guardado. Comprueba el estado de cada envío.':'Cambios guardados.');}catch(e){notice(e.message);if(current?.id){try{const fresh=await request(api+'?id='+encodeURIComponent(current.id));if(fresh.status==='signed'){current=fresh;show();}}catch{}}$('completion').textContent=e.message;}finally{busy=false;for(const b of $('document-form').querySelectorAll('button'))b.disabled=false;}}
$('document-form').onsubmit=e=>{e.preventDefault();act(current?'update':'create',{title:$('title').value,content:$('content').value,category:$('category').value,serviceCode:$('service').value,entityType:$('entityType').value,entityId:$('entityId').value});};
const dirty=()=>current?($('title').value!==current.title||$('content').value!==current.content):Boolean($('title').value||$('content').value);
function ready(){if(dirty()){$('completion').textContent='Guarda los cambios antes de continuar.';return false;}if(missing($('content').value).length){$('completion').textContent='Completa todos los campos antes de dar conformidad o firmar.';return false;}return true;}
$('review').onclick=()=>{selectTab('read');if(ready())act('review');};
$('prepare-sign').onclick=()=>{if(!ready())return;$('sign-panel').hidden=false;for(const n of ['read','info','activity'])$(n+'-pane').hidden=true;$('signer').value='';$('recipients').value='';$('consent').checked=false;clearSignature();};
const canvas=$('signature'),ctx=canvas.getContext('2d');ctx.lineWidth=2.5;ctx.lineCap='round';ctx.strokeStyle='#111';
function point(e){const r=canvas.getBoundingClientRect();return [(e.clientX-r.left)*canvas.width/r.width,(e.clientY-r.top)*canvas.height/r.height];}
canvas.onpointerdown=e=>{drawing=true;canvas.setPointerCapture(e.pointerId);ctx.beginPath();ctx.moveTo(...point(e));};canvas.onpointermove=e=>{if(!drawing)return;ctx.lineTo(...point(e));ctx.stroke();signedStroke=true;};canvas.onpointerup=canvas.onpointercancel=()=>{drawing=false;};
function clearSignature(){ctx.clearRect(0,0,canvas.width,canvas.height);signedStroke=false;}$('clear').onclick=clearSignature;
$('sign').onclick=()=>{selectTab('read');if(!signedStroke||!$('consent').checked||$('signer').value.trim().length<2){$('completion').textContent='Escribe el nombre, dibuja la firma y acepta el documento.';return;}if(!ready())return;const recipients=$('recipients').value.split(',').map(s=>s.trim()).filter(Boolean);act('sign',{signer:$('signer').value.trim(),signature:canvas.toDataURL('image/png'),consent:true,recipients});};
$('create-copy').onclick=()=>{copySource=current;$('fields').replaceChildren();$('builder-error').textContent='';$('builder-title').textContent=current.title;$('copy-service').value=scope||current.service_code||'';for(const key of missing(current.content)){const label=document.createElement('label'),input=document.createElement('textarea');label.textContent=key.replaceAll('_',' ').toLowerCase();input.name=key;input.required=true;input.maxLength=8000;input.rows=2;if(key==='FECHA')input.value=new Date().toLocaleDateString('es-ES');label.append(input);$('fields').append(label);}$('builder').showModal();};
$('builder-form').onsubmit=async e=>{e.preventDefault();if(busy)return;const values=Object.fromEntries(new FormData($('builder-form')));const content=copySource.content.replace(/\{\{([A-Z0-9_]+)\}\}/g,(_,key)=>String(values[key]||'').trim());if(missing(content).length||Object.values(values).some(v=>!String(v).trim())){$('builder-error').textContent='Completa todos los datos.';return;}if(content.length>100000){$('builder-error').textContent='El documento excede el tamaño permitido.';return;}busy=true;$('builder-form').querySelector('button[type=submit]').disabled=true;try{const ref=String(values.EXPEDIENTE||'Copia').slice(0,80);const d=await request(api,{action:'create',title:(copySource.title+' · '+ref).slice(0,200),category:copySource.category,serviceCode:$('copy-service').value,entityType:copySource.category==='colaboradores'?'colaborador':copySource.category==='organizacion'?'departamento':'cliente',entityId:ref,content});current=await request(api+'?id='+encodeURIComponent(d.id));$('builder').close();show();$('collection').value='records';await load();notice('Copia completa creada. Lee el documento antes de dar conformidad y firmar.');}catch(err){$('builder-error').textContent=err.message;}finally{busy=false;$('builder-form').querySelector('button[type=submit]').disabled=false;}};
$('builder-close').onclick=()=>{if(!busy)$('builder').close();};$('builder').addEventListener('cancel',e=>{if(busy)e.preventDefault();});
$('send').onclick=()=>act('send');$('close').onclick=()=>{if(!busy&&(!dirty()||confirm('¿Cerrar sin guardar los cambios?')))closeEditor();};$('editor').addEventListener('cancel',e=>{if(busy||dirty())e.preventDefault();});$('new').onclick=()=>open(null);$('refresh').onclick=load;$('search').oninput=render;$('filter').onchange=render;$('collection').onchange=render;$('sort').onchange=render;$('content').oninput=$('title').oninput=readText;$('print').onclick=()=>window.print();$('scope').textContent=scope?'Documentación del servicio '+scope+' · Modelos generales disponibles para preparar copias':'Biblioteca de documentos completos y expedientes';load();

function closeEditor(){$('editor').close();document.body.classList.remove('reader-open');current=null;render();$('search').focus();}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>selectTab(b.dataset.tab));
document.querySelectorAll('[data-view]').forEach((b,i)=>{b.prepend(icon(['file-earmark-text','folder2-open','pen','check2-circle'][i]));b.onclick=()=>{$('collection').value=b.dataset.view;$('filter').value='';$('search').value='';render();document.body.classList.remove('nav-open');$('menu-toggle').setAttribute('aria-expanded','false');};});
document.querySelectorAll('[data-area]').forEach(b=>{b.prepend(icon({clientes:'people',servicios:'briefcase',legal:'shield-check',organizacion:'gear'}[b.dataset.area]||'folder2-open'));b.onclick=()=>{$('filter').value=b.dataset.area;$('collection').value='all';render();document.body.classList.remove('nav-open');$('menu-toggle').setAttribute('aria-expanded','false');};});
$('menu-toggle').onclick=()=>{const v=document.body.classList.toggle('nav-open');$('menu-toggle').setAttribute('aria-expanded',String(v));};
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('builder').open&&$('editor').open){e.preventDefault();$('close').click();}if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();$('search').focus();}});

const tabs=[...document.querySelectorAll('[data-tab]')];tabs.forEach((b,i)=>{b.id='tab-'+b.dataset.tab;b.setAttribute('aria-controls',b.dataset.tab+'-pane');$(b.dataset.tab+'-pane').setAttribute('aria-labelledby',b.id);b.onkeydown=e=>{if(!['ArrowRight','ArrowLeft','Home','End'].includes(e.key))return;e.preventDefault();const n=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:tabs.length-1))%tabs.length;selectTab(tabs[n].dataset.tab);tabs[n].focus();};});
