'use client';
import {useState} from 'react';
import {useTiendaEstado} from '@/store/useTiendaEstado';
type Proposal={operation:'design'|'marketing'|'campaign';proposal:Record<string,string>};
export function AIProposal(){
 const [balance,setBalance]=useState<number|null>(null);
 const [operation,setOperation]=useState<'design'|'marketing'|'campaign'>('design'),[brief,setBrief]=useState(''),[result,setResult]=useState<Proposal|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[cost,setCost]=useState<number|null>(null),[accepted,setAccepted]=useState(false);
 async function quote(){setError('');setBusy(true);try{const r=await fetch('/api/ai-quote?operation='+operation,{cache:'no-store'});const a=await r.json();if(!r.ok||!a.available)throw Error(a.error || 'La tarifa de IA no está activada. Puedes editar manualmente.');setCost(a.cost);setBalance(a.balance);}catch(e){setError(e instanceof Error?e.message:'No se pudo consultar el coste.');}finally{setBusy(false);}}
 async function generate(){setBusy(true);setError('');setResult(null);setAccepted(false);try{const s=useTiendaEstado.getState();const r=await fetch('/api/ai-proposal',{method:'POST',headers:{'Content-Type':'application/json','x-request-id':crypto.randomUUID()},body:JSON.stringify({operation,brief,expectedCost:cost,name:s.adnMarca?.analisisVision?.nombreSugerido||''})});const data=await r.json();if(!r.ok){setCost(null);throw Error(data.error);}setResult(data);setBalance(v=>v===null?v:v-(cost||0));window.dispatchEvent(new Event('innova-account-updated'));}catch(e){setError(e instanceof Error?e.message:'No se pudo generar.');}finally{setBusy(false);}}
 function apply(){if(!result)return;const s=useTiendaEstado.getState(),d=s.datosEscaparate;if(!s.adnMarca||!d)return;const p=result.proposal;
  if(result.operation==='design'||result.operation==='campaign'){s.actualizarAdn({paletaColores:{...s.adnMarca.paletaColores,primario:p.primario,secundario:p.secundario,acento:p.acento,fondo:p.fondo}});s.regenerarEscaparate({...d,disenoSeleccionado:p.layout as typeof d.disenoSeleccionado});}
  if(result.operation==='marketing'||result.operation==='campaign'){s.regenerarEscaparate({...useTiendaEstado.getState().datosEscaparate!,datosReales:{...d.datosReales,titularPrincipal:p.titulo,descripcionValor:p.descripcion,ctaPrincipal:p.cta}});}
  setResult(null);setAccepted(true);
 }
 return <section className="studio-panel space-y-4"><h2 className="text-xl font-semibold">Preparar una propuesta con IA</h2><p className="studio-muted">La propuesta no se publica automáticamente. Cambiar el diseño conserva tus textos, servicios y contactos. Las regeneraciones de campaña consumen créditos del plan aunque descartes una propuesta válida.</p><label className="studio-field">Qué quieres mejorar<select value={operation} disabled={busy} onChange={e=>{setOperation(e.target.value as 'design'|'marketing'|'campaign');setResult(null);setCost(null);}}><option value="design">Diseño y colores</option><option value="marketing">Mensaje de marketing</option><option value="campaign">Diseño y marketing juntos</option></select></label><label className="studio-field">Describe el cambio<textarea value={brief} maxLength={5000} onChange={e=>setBrief(e.target.value)} /></label>{cost===null?<button className="studio-button" disabled={busy} onClick={quote}>Consultar coste</button>:<button className="studio-primary" disabled={busy||!brief.trim()||(balance!==null&&cost!==null&&balance<cost)} onClick={generate}>{busy?'Preparando…':`Generar propuesta · ${cost} créditos`}</button>}{cost!==null&&<p>Saldo: {balance} créditos · Coste: {cost} créditos.</p>}{balance!==null&&cost!==null&&balance<cost&&<a className="studio-button" href="/checkout?kind=credits">Recargar créditos</a>}{error&&<p role="alert">{error}</p>}{accepted&&<p role="status">Propuesta aplicada al borrador. Revisa la vista previa antes de publicar.</p>}{result&&<div className="space-y-3"><h3 className="font-semibold">Revisa la propuesta</h3><dl>{Object.entries(result.proposal).map(([k,v])=><div key={k}><dt className="font-semibold">{k}</dt><dd>{v}</dd></div>)}</dl><button className="studio-primary" onClick={apply}>Aplicar al borrador</button><button className="studio-button ml-3" onClick={()=>setResult(null)}>Descartar</button></div>}</section>;
}
