"use client";
import { useState } from 'react';
import type { AdnMarca } from '@/lib/estado/tipos-estado';
import { useTiendaEstado } from '@/store/useTiendaEstado';
export default function InformeIdentidad({adn,onConfirmar}:{adn:AdnMarca;onConfirmar:()=>void|Promise<void>}) {
 const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 const update=useTiendaEstado(s=>s.actualizarAdn);
 async function confirm(){setBusy(true);setError('');try{await onConfirmar();}catch{setError('No se pudo preparar el diseño. Inténtalo otra vez.');}finally{setBusy(false);}}
 return <div className="studio-panel max-w-2xl mx-auto space-y-6"><div><h2 className="text-2xl font-semibold">Confirma los datos básicos</h2><p className="studio-muted mt-2">Puedes corregirlos ahora y seguir editándolos después.</p></div>{!adn.analisisVision?.confianzaAnalisis && <p className="studio-notice">El análisis automático no está disponible. Completa el nombre y el sector para continuar en modo manual.</p>}<label className="studio-field">Nombre comercial<input value={adn.analisisVision?.nombreSugerido||''} onChange={e=>adn.analisisVision&&update({analisisVision:{...adn.analisisVision,nombreSugerido:e.target.value}})} /></label><label className="studio-field">Sector o tipo de negocio<input value={adn.analisisVision?.categoriaSugerida||''} onChange={e=>adn.analisisVision&&update({analisisVision:{...adn.analisisVision,categoriaSugerida:e.target.value}})} /><span className="studio-muted text-sm">Por ejemplo: restaurante, peluquería, clínica o tienda de moda.</span></label><label className="studio-field">Descripción del negocio<textarea rows={4} value={adn.analisisMarketing||''} onChange={e=>update({analisisMarketing:e.target.value})}/></label>{error&&<p role="alert" className="text-red-300">{error}</p>}<button className="studio-primary w-full" disabled={busy||!adn.analisisVision?.nombreSugerido.trim()||!adn.analisisVision?.categoriaSugerida.trim()} onClick={confirm}>{busy?'Preparando tu diseño…':'Confirmar identidad y ver diseño'}</button></div>;
}
