// Brand data extracted from storefront image
export interface BrandData {
    name: string;
    businessType: string;
    niche?: string;
    tagline?: string;
    description: string;
    colors: {
        primary: string;
        secondary: string;
        accent: string;
    };
    typography: string;
    style: string;
    logoUrl?: string;
    targetAudience?: string;
    instagram?: string;
    facebook?: string;
    whatsapp?: string;
    address?: string;
    hours?: string;
}

// Marketing strategy generated by AI
export interface WidgetConfigField {
    key: string;
    label: string;
    type: 'text' | 'number' | 'color' | 'tel' | 'email' | 'textarea' | 'list';
    default?: string;
    placeholder?: string;
}

export interface GenerativeStrategy {
    id: string;
    emoji: string;
    title: string;
    description: string;
    ui_config_schema: WidgetConfigField[];
    code_template: string;
}

export interface MarketingStrategy {
    id: string;
    title: string;
    description: string;
    reasoning: string;
    tactics: string[];
    seasonalContext?: string;
    locationContext?: string;
    // New fields for Generative Engine (optional for backward compatibility)
    emoji?: string;
    code_template?: string;
    ui_config_schema?: WidgetConfigField[];
}

// Link/feature for the landing page
export interface LandingLink {
    id: string;
    name: string;
    emoji: string;
    description: string;
    type: 'gamification' | 'reservation' | 'menu' | 'contact' | 'social' | 'promo' | 'info';
    engagement: 'low' | 'medium' | 'high' | 'very-high';
    conversion: 'low' | 'medium' | 'high' | 'very-high';
    isPremium: boolean;
    regenerateCount: number;
    url?: string; // Generated URL for this specific link's content page
}

// Landing page configuration
// Landing page styling configuration
export interface LandingPageConfig {
    background: {
        type: 'solid' | 'gradient' | 'image' | 'texture';
        value: string; // Hex color, gradient string, image URL, or texture ID
        overlay?: string; // Optional overlay color/opacity (e.g. "rgba(0,0,0,0.5)")
    };
    header: {
        logoSize: number; // 60-120
        titleColor: string;
        subtitleColor: string;
        layout: 'centered' | 'left';
    };
    buttons: {
        style: 'pill' | 'rounded' | 'sharp' | 'glass';
        background: string;
        textColor: string;
        border?: string;
        shadow?: string;
    };
    separators: {
        top?: 'wave' | 'zigzag' | 'dome' | 'none';
        bottom?: 'wave' | 'zigzag' | 'dome' | 'none';
        color: string;
    };
    font: string;
}

export interface LandingConfig {
    id: string;
    name: string;
    brand: BrandData;
    links: LandingLink[];
    // Replaced simple "template" string with full config object
    // We allow a "presetId" to track which theme started it, but "config" holds the real data
    presetId?: string;
    config: LandingPageConfig;
    createdAt: Date;
    updatedAt: Date;
}

// Project containing multiple landings/campaigns
export interface Project {
    id: string;
    name: string;
    description?: string;
    campaign?: string; // e.g., "Navidad 2024", "Black Friday"
    landings: LandingConfig[];
    status: 'active' | 'draft' | 'archived';
    createdAt: Date;
    updatedAt: Date;
}

// User subscription tier
export type SubscriptionTier = 'free' | 'plus' | 'pro' | 'premium';
export type UserTier = SubscriptionTier; // Alias for convenience

// User data
export interface User {
    id: string;
    email: string;
    name?: string;
    tier: SubscriptionTier;
    projects: Project[];
    limits: UserLimits;
}

// Usage limits based on subscription
export interface UserLimits {
    maxProjects: number;
    maxLandingsPerProject: number;
    maxLinkRegenerations: number;
    availableTemplates: number;
    hasAnalytics: boolean;
    hasPremiumFeatures: boolean;
    posterHasWatermark: boolean;
}

// Subscription tier limits
export const TIER_LIMITS: Record<SubscriptionTier, UserLimits> = {
    free: {
        maxProjects: 1,
        maxLandingsPerProject: 1,
        maxLinkRegenerations: 3,
        availableTemplates: 2,
        hasAnalytics: false,
        hasPremiumFeatures: false,
        posterHasWatermark: true
    },
    plus: {
        maxProjects: 5,
        maxLandingsPerProject: 3,
        maxLinkRegenerations: 10,
        availableTemplates: 4,
        hasAnalytics: true,
        hasPremiumFeatures: false,
        posterHasWatermark: false
    },
    pro: {
        maxProjects: 20,
        maxLandingsPerProject: 10,
        maxLinkRegenerations: -1, // unlimited
        availableTemplates: 4,
        hasAnalytics: true,
        hasPremiumFeatures: true,
        posterHasWatermark: false
    },
    premium: {
        maxProjects: -1, // unlimited
        maxLandingsPerProject: -1,
        maxLinkRegenerations: -1,
        availableTemplates: 4,
        hasAnalytics: true,
        hasPremiumFeatures: true,
        posterHasWatermark: false
    }
};

// App flow step
export type FlowStep = 'upload' | 'analysis' | 'strategy' | 'links' | 'design' | 'poster' | 'complete';

export const FLOW_STEPS: { id: FlowStep; name: string; icon: string }[] = [
    { id: 'upload', name: 'Subir Foto', icon: 'Camera' },
    { id: 'analysis', name: 'Análisis', icon: 'Sparkles' },
    { id: 'strategy', name: 'Estrategias', icon: 'Target' },
    { id: 'links', name: 'Enlaces', icon: 'Link' },
    { id: 'design', name: 'Diseño', icon: 'Layout' },
    { id: 'poster', name: 'Cartel QR', icon: 'QrCode' }
];

// API Response types
export interface VisionAnalysisResponse {
    success: boolean;
    data?: BrandData;
    error?: string;
}

export interface StrategyGenerationResponse {
    success: boolean;
    strategies?: MarketingStrategy[];
    error?: string;
}

export interface LinksGenerationResponse {
    success: boolean;
    links?: LandingLink[];
    error?: string;
}
